<?php

namespace Database\Seeders\Main;

use App\Models\Glossary\Glossary_DivisionType;
use App\Models\Main\Main_Division;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DivisionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        /* TYPES */
        Glossary_DivisionType::create(['id' => 1, 'name' => 'УСЗН | КСЗН | КСП']);
        Glossary_DivisionType::create(['id' => 2, 'name' => 'Подведомственная организация']);
        Glossary_DivisionType::create(['id' => 3, 'name' => 'Министерство']);
        Glossary_DivisionType::create(['id' => 4, 'name' => 'Частная организация']);

        /* DIVISION */
        Main_Division::create(['id' => 1, 'name' => 'Министерство СЗН', 'type_id' => 3, 'city_id' => 7]);
        Main_Division::create(['id' => 2, 'name' => 'ГКУ ЦСВИ', 'type_id' => 2, 'city_id' => 7]);
        Main_Division::create(['id' => 3, 'name' => 'ГАУ Журавлевский дом-интернат для престарелых и инвалидов', 'type_id' => 2, 'city_id' => 7]);
        Main_Division::create(['id' => 4, 'name' => 'МКУ ЦСО ГПВиИ', 'type_id' => 2, 'city_id' => 22]);
        Main_Division::create(['id' => 5, 'name' => 'АНО "Жизнь"', 'type_id' => 4, 'city_id' => 1]);
        Main_Division::create(['id' => 6, 'name' => 'БФ "Загадай желание"', 'type_id' => 4, 'city_id' => 1]);
        Main_Division::create(['id' => 7, 'name' => 'ГБУ "Анжеро-Судженский дом -интернат для граждан, имеющих психические расстройства"', 'type_id' => 2, 'city_id' => 1]);
        Main_Division::create(['id' => 8, 'name' => 'МБУ "Анжеро-Судженский КЦСОН"', 'type_id' => 2, 'city_id' => 1]);
        Main_Division::create(['id' => 9, 'name' => 'МКУ "Реабилитационный центр"', 'type_id' => 2, 'city_id' => 1]);
        Main_Division::create(['id' => 10, 'name' => 'МКУ СРЦ для несовершеннолетних', 'type_id' => 2, 'city_id' => 1]);
        Main_Division::create(['id' => 11, 'name' => 'ГБУ "Евтинский ДДИ для детей с ментальными нарушениями"', 'type_id' => 2, 'city_id' => 2]);
        Main_Division::create(['id' => 12, 'name' => 'ГБУ "Инской дом-интернат для граждан, имеющих психические расстройства"', 'type_id' => 2, 'city_id' => 2]);
        Main_Division::create(['id' => 13, 'name' => 'МБУ "ЦСО" г.Белово', 'type_id' => 2, 'city_id' => 2]);
        Main_Division::create(['id' => 14, 'name' => 'МКУ ЦСОН', 'type_id' => 2, 'city_id' => 2]);
        Main_Division::create(['id' => 15, 'name' => 'МКУ СРЦ "Теплый дом"', 'type_id' => 2, 'city_id' => 2]);
        Main_Division::create(['id' => 16, 'name' => 'МКУ ЦСПСиД', 'type_id' => 2, 'city_id' => 2]);
        Main_Division::create(['id' => 17, 'name' => 'ООО "Чибисы"', 'type_id' => 4, 'city_id' => 2]);
        Main_Division::create(['id' => 18, 'name' => 'МБУ ЦСО Березовского ГО', 'type_id' => 2, 'city_id' => 3]);
        Main_Division::create(['id' => 19, 'name' => 'МКУ СРЦ "Берегиня"', 'type_id' => 2, 'city_id' => 3]);
        Main_Division::create(['id' => 20, 'name' => 'ГКУ "Гурьевский дом-интернат для граждан, имеющих психические расстройства"', 'type_id' => 2, 'city_id' => 4]);
        Main_Division::create(['id' => 21, 'name' => 'МКУ СРЦ для несовершеннолетних"', 'type_id' => 2, 'city_id' => 4]);
        Main_Division::create(['id' => 22, 'name' => 'МКУ ЦСО', 'type_id' => 2, 'city_id' => 4]);
        Main_Division::create(['id' => 23, 'name' => 'МБУ "КЦСОН" Ижморский МР', 'type_id' => 2, 'city_id' => 5]);
        Main_Division::create(['id' => 24, 'name' => 'АНО "Центр Социального Развития"', 'type_id' => 4, 'city_id' => 6]);
        Main_Division::create(['id' => 25, 'name' => 'ГБУ "Малиновский дом-интернат для граждан, имеющих психические расстройства"', 'type_id' => 2, 'city_id' => 6]);
        Main_Division::create(['id' => 26, 'name' => 'МКУ ЦСО КГО', 'type_id' => 2, 'city_id' => 6]);
        Main_Division::create(['id' => 27, 'name' => 'МКУ ЦСПСД', 'type_id' => 2, 'city_id' => 6]);
        Main_Division::create(['id' => 28, 'name' => 'АНО "Православная патронажная служба"', 'type_id' => 4, 'city_id' => 7]);
        Main_Division::create(['id' => 29, 'name' => 'АНО пансионат по уходу за пожилыми иинвалидами "ВероНика"', 'type_id' => 4, 'city_id' => 7]);
        Main_Division::create(['id' => 30, 'name' => 'АНО Психологический центр "СемьЯ"', 'type_id' => 4, 'city_id' => 7]);
        Main_Division::create(['id' => 31, 'name' => 'АНО Дом-интернат для престарелых и инвалидов "Семеновна"', 'type_id' => 4, 'city_id' => 7]);
        Main_Division::create(['id' => 32, 'name' => 'АНО Пансионат для пожилых людей "Доброе сердце"', 'type_id' => 4, 'city_id' => 7]);
        Main_Division::create(['id' => 33, 'name' => 'АНО "Социальный скреп"', 'type_id' => 4, 'city_id' => 7]);
        Main_Division::create(['id' => 34, 'name' => 'АНО "ВОСХОЖДЕНИЕ"', 'type_id' => 4, 'city_id' => 7]);
        Main_Division::create(['id' => 35, 'name' => 'ГАУ "Кемеровский дом-интернат для престарелых и инвалидов"', 'type_id' => 2, 'city_id' => 7]);
        Main_Division::create(['id' => 36, 'name' => 'ГАУ "Кемеровский центр социальной адаптации населения"', 'type_id' => 2, 'city_id' => 7]);
        Main_Division::create(['id' => 37, 'name' => 'ГБУ "Кедровский дом-интернат для граждан, имеющих психические расстройства"', 'type_id' => 2, 'city_id' => 7]);
        Main_Division::create(['id' => 38, 'name' => 'ГКУ СРЦ для несовершеннолетних "Маленький принц"', 'type_id' => 2, 'city_id' => 7]);
        Main_Division::create(['id' => 39, 'name' => 'ГАУ "Фламинго"', 'type_id' => 4, 'city_id' => 7]);
        Main_Division::create(['id' => 40, 'name' => 'КГОО "Интеграция"', 'type_id' => 4, 'city_id' => 7]);
        Main_Division::create(['id' => 41, 'name' => 'МАУ "КЦСОН Кировского района г. Кемерово"', 'type_id' => 2, 'city_id' => 7]);
        Main_Division::create(['id' => 42, 'name' => 'МБУ "КЦСОН ж.р.Кедровка г.Кемерово"', 'type_id' => 2, 'city_id' => 7]);
        Main_Division::create(['id' => 43, 'name' => 'МБУ "КЦСОН Заводского района г. Кемерово"', 'type_id' => 2, 'city_id' => 7]);
        Main_Division::create(['id' => 44, 'name' => 'МБУ "КЦСОН Ленинского района г. Кемерово"', 'type_id' => 2, 'city_id' => 7]);
        Main_Division::create(['id' => 45, 'name' => 'МБУ "КЦСОН Рудничного района г. Кемерово"', 'type_id' => 2, 'city_id' => 7]);
        Main_Division::create(['id' => 46, 'name' => 'МБУ "КЦСОН Центрального района г. Кемерово"', 'type_id' => 2, 'city_id' => 7]);
        Main_Division::create(['id' => 47, 'name' => 'МКУ "КЦСОН Кемеровского МО"', 'type_id' => 2, 'city_id' => 7]);
        Main_Division::create(['id' => 48, 'name' => 'МКУ ЦСПСиД', 'type_id' => 2, 'city_id' => 7]);
        Main_Division::create(['id' => 49, 'name' => 'НКО КРОО "Новые горизонты"', 'type_id' => 4, 'city_id' => 7]);
        Main_Division::create(['id' => 50, 'name' => 'ООО "Гармония"', 'type_id' => 4, 'city_id' => 7]);
        Main_Division::create(['id' => 51, 'name' => 'РОО ООО "Всероссийское ордена Трудового Красного Знамени общество слепых"', 'type_id' => 4, 'city_id' => 7]);
        Main_Division::create(['id' => 52, 'name' => 'МКУ ЦСО', 'type_id' => 2, 'city_id' => 9]);
        Main_Division::create(['id' => 53, 'name' => 'МКУ СРЦ "Доверие"', 'type_id' => 2, 'city_id' => 9]);
        Main_Division::create(['id' => 54, 'name' => 'МБУ КЦСОН Крапивинского МО', 'type_id' => 2, 'city_id' => 10]);
        Main_Division::create(['id' => 55, 'name' => 'МКУ СРЦ для несовершеннолетних', 'type_id' => 2, 'city_id' => 10]);
        Main_Division::create(['id' => 56, 'name' => 'ООО "Ренессанс"', 'type_id' => 4, 'city_id' => 10]);
        Main_Division::create(['id' => 57, 'name' => 'ГБУ "Краснинский дом-интернат для граждан, имеющих психические расстройства"', 'type_id' => 2, 'city_id' => 12]);
        Main_Division::create(['id' => 58, 'name' => 'ГБУ "Ленинск-Кузнецкий реабилитационный центр для детей и подростков с ограниченными возможностями"', 'type_id' => 2, 'city_id' => 12]);
        Main_Division::create(['id' => 59, 'name' => 'МБУ ЦСОН г.Ленинск-Кузнецкий', 'type_id' => 2, 'city_id' => 12]);
        Main_Division::create(['id' => 60, 'name' => 'МКУ СРЦ "Надежда"', 'type_id' => 2, 'city_id' => 12]);
        Main_Division::create(['id' => 61, 'name' => 'МКУ СРЦ "Радуга"', 'type_id' => 2, 'city_id' => 12]);
        Main_Division::create(['id' => 62, 'name' => 'МКУ ЦСО ГПВИИ', 'type_id' => 2, 'city_id' => 12]);
        Main_Division::create(['id' => 63, 'name' => 'АНО Центр Социальной Помощи "Гавань Надежды"', 'type_id' => 4, 'city_id' => 13]);
        Main_Division::create(['id' => 64, 'name' => 'ГБУ "Благовещенский дом-интернат для граждан, имеющих психические расстройства"', 'type_id' => 2, 'city_id' => 13]);
        Main_Division::create(['id' => 65, 'name' => 'ГБУ "Мариинский дом-интернат для граждан, имеющих психические расстройства"', 'type_id' => 2, 'city_id' => 13]);
        Main_Division::create(['id' => 66, 'name' => 'ГБУ "Мариинский реабилитационный центр для детей и подростков с ограниченными возможностями"', 'type_id' => 2, 'city_id' => 13]);
        Main_Division::create(['id' => 67, 'name' => 'МБУ "КЦСОН" Мариинского МР', 'type_id' => 2, 'city_id' => 13]);
        Main_Division::create(['id' => 68, 'name' => 'МКУ СРЦ для несовершеннолетних"', 'type_id' => 2, 'city_id' => 13]);
        Main_Division::create(['id' => 69, 'name' => 'ГБУ "Междуреченский дом-интернат для граждан, имеющих психические расстройства"', 'type_id' => 2, 'city_id' => 14]);
        Main_Division::create(['id' => 70, 'name' => 'МБУ КЦСОН г.Междуреченск', 'type_id' => 2, 'city_id' => 14]);
        Main_Division::create(['id' => 71, 'name' => 'МКУ СРЦ для несовершеннолетних', 'type_id' => 2, 'city_id' => 14]);
        Main_Division::create(['id' => 72, 'name' => 'МКУ ЦСПСиД', 'type_id' => 2, 'city_id' => 14]);
        Main_Division::create(['id' => 73, 'name' => 'ГБУ "Мысковский ДДИ для детей с ментальными нарушениями"', 'type_id' => 2, 'city_id' => 15]);
        Main_Division::create(['id' => 74, 'name' => 'МКУ СРЦ для несовершеннолетних', 'type_id' => 2, 'city_id' => 15]);
        Main_Division::create(['id' => 75, 'name' => 'МКУ ЦСОН', 'type_id' => 2, 'city_id' => 15]);
        Main_Division::create(['id' => 76, 'name' => 'БФ "Источник жизни"', 'type_id' => 4, 'city_id' => 16]);
        Main_Division::create(['id' => 77, 'name' => 'ГКУ "Новокузнецкий дом-интернат для престарелых и инвалидов"', 'type_id' => 2, 'city_id' => 16]);
        Main_Division::create(['id' => 79, 'name' => 'МБУ КЦСОН Кузнецкого района', 'type_id' => 2, 'city_id' => 16]);
        Main_Division::create(['id' => 80, 'name' => 'МБУ КЦСОН Куйбышевского района', 'type_id' => 2, 'city_id' => 16]);
        Main_Division::create(['id' => 81, 'name' => 'МБУ КЦСОН Новоильинского района', 'type_id' => 2, 'city_id' => 16]);
        Main_Division::create(['id' => 82, 'name' => 'МБУ КЦСОН Орджоникидзевского района', 'type_id' => 2, 'city_id' => 16]);
        Main_Division::create(['id' => 83, 'name' => 'МБУ КЦСОН Центрального района', 'type_id' => 2, 'city_id' => 16]);
        Main_Division::create(['id' => 84, 'name' => 'МКУ Дом ночного пребывания для лиц без определенного места жительства и занятий', 'type_id' => 2, 'city_id' => 16]);
        Main_Division::create(['id' => 85, 'name' => 'МКУ КЦСОН МО "НМО Кемеровской области-Кузбасса"', 'type_id' => 2, 'city_id' => 16]);
        Main_Division::create(['id' => 86, 'name' => 'МКУ СРЦ "Алые паруса"', 'type_id' => 2, 'city_id' => 16]);
        Main_Division::create(['id' => 87, 'name' => 'МКУ СРЦ "Полярная звезда"', 'type_id' => 2, 'city_id' => 16]);
        Main_Division::create(['id' => 88, 'name' => 'МКУ СРЦ "Уютный дом"', 'type_id' => 2, 'city_id' => 16]);
        Main_Division::create(['id' => 89, 'name' => 'МКУ ЦСПСиД', 'type_id' => 2, 'city_id' => 16]);
        Main_Division::create(['id' => 90, 'name' => 'МКУ "Центр социальной помощи семье и детям"', 'type_id' => 2, 'city_id' => 16]);
        Main_Division::create(['id' => 91, 'name' => 'МКУ Центр реабилитации детей и подростков сограниченными возможностями', 'type_id' => 2, 'city_id' => 16]);
        Main_Division::create(['id' => 92, 'name' => 'ООО "Росток"', 'type_id' => 4, 'city_id' => 16]);
        Main_Division::create(['id' => 93, 'name' => 'ООО "Здоровье"', 'type_id' => 4, 'city_id' => 16]);
        Main_Division::create(['id' => 94, 'name' => 'ООО "Здоровье-НК"', 'type_id' => 4, 'city_id' => 16]);
        Main_Division::create(['id' => 95, 'name' => 'МБУ ЦСО ОГО', 'type_id' => 2, 'city_id' => 17]);
        Main_Division::create(['id' => 96, 'name' => 'МКУ ЦСПСиД', 'type_id' => 2, 'city_id' => 17]);
        Main_Division::create(['id' => 97, 'name' => 'МБУ "КЦСОН"', 'type_id' => 2, 'city_id' => 18]);
        Main_Division::create(['id' => 98, 'name' => 'ГБУ "Прокопьевский дом-интернат для граждан, имеющих психические расстройства"', 'type_id' => 2, 'city_id' => 19]);
        Main_Division::create(['id' => 99, 'name' => 'КРООБН "Дом свободы"', 'type_id' => 4, 'city_id' => 19]);
        Main_Division::create(['id' => 100, 'name' => 'МБУ "ЦСОН"', 'type_id' => 2, 'city_id' => 19]);
        Main_Division::create(['id' => 101, 'name' => 'МКУ СРЦ для несовершеннолетних "Алиса"', 'type_id' => 2, 'city_id' => 19]);
        Main_Division::create(['id' => 102, 'name' => 'МКУ Центр организации социального обслуживания г. Прокопьевска', 'type_id' => 2, 'city_id' => 19]);
        Main_Division::create(['id' => 103, 'name' => 'МКУ ЦСО', 'type_id' => 2, 'city_id' => 19]);
        Main_Division::create(['id' => 104, 'name' => 'МКУ СРЦ для несовершеннолетних', 'type_id' => 2, 'city_id' => 19]);
        Main_Division::create(['id' => 105, 'name' => 'МБУ "КЦСОН" Промышленновского МО', 'type_id' => 2, 'city_id' => 20]);
        Main_Division::create(['id' => 106, 'name' => 'ГБУ "Тайгинский дом-интернат для граждан, имеющих психические расстройства"', 'type_id' => 2, 'city_id' => 21]);
        Main_Division::create(['id' => 107, 'name' => 'МБУ "КЦСОН" ТГО', 'type_id' => 2, 'city_id' => 21]);
        Main_Division::create(['id' => 108, 'name' => 'МКУ СРЦ для несовершеннолетних"', 'type_id' => 2, 'city_id' => 21]);
        Main_Division::create(['id' => 110, 'name' => 'МКУ СРЦ для несовершеннолетних', 'type_id' => 2, 'city_id' => 22]);
        Main_Division::create(['id' => 111, 'name' => 'ГБУ "Листвянский дом-интернат для граждан, имеющих психические расстройства"', 'type_id' => 2, 'city_id' => 23]);
        Main_Division::create(['id' => 112, 'name' => 'МКУ ТСРЦ', 'type_id' => 2, 'city_id' => 23]);
        Main_Division::create(['id' => 113, 'name' => 'МКУ ЦСО', 'type_id' => 2, 'city_id' => 23]);
        Main_Division::create(['id' => 114, 'name' => 'МБУ "Топкинский ЦСО"', 'type_id' => 2, 'city_id' => 24]);
        Main_Division::create(['id' => 115, 'name' => 'МКУ СРЦ "Центр Семья"', 'type_id' => 2, 'city_id' => 24]);
        Main_Division::create(['id' => 116, 'name' => 'ГКУ "Кубитетский специальный дом-интернат для престарелых и инвалидов"', 'type_id' => 2, 'city_id' => 25]);
        Main_Division::create(['id' => 117, 'name' => 'МБУ ЦСОН Тяжинского МО', 'type_id' => 2, 'city_id' => 25]);
        Main_Division::create(['id' => 118, 'name' => 'МКУ СРЦ для несовершеннолетних"', 'type_id' => 2, 'city_id' => 25]);
        Main_Division::create(['id' => 119, 'name' => 'МКУ "КЦСОН" Чебулинского МО', 'type_id' => 2, 'city_id' => 26]);
        Main_Division::create(['id' => 120, 'name' => 'ГАУ "Юргинский дом-интернат для граждан, имеющих психические расстройства"', 'type_id' => 2, 'city_id' => 27]);
        Main_Division::create(['id' => 121, 'name' => 'ГАУ "Юргинский дом-интернат для престарелых и инвалидов"', 'type_id' => 2, 'city_id' => 27]);
        Main_Division::create(['id' => 122, 'name' => 'ГБУ "Юргинский ДДИ для детей с ментальными нарушениями"', 'type_id' => 2, 'city_id' => 27]);
        Main_Division::create(['id' => 123, 'name' => 'МБУ "ЦСО ГПВиИ г. Юрги"', 'type_id' => 2, 'city_id' => 27]);
        Main_Division::create(['id' => 124, 'name' => 'МКУ "КЦСОН Юргинского МО"', 'type_id' => 2, 'city_id' => 27]);
        Main_Division::create(['id' => 125, 'name' => 'МКУ СРЦ для несовершеннолетних "Солнышко"', 'type_id' => 2, 'city_id' => 27]);
        Main_Division::create(['id' => 126, 'name' => 'МКУ ЦСПСиД', 'type_id' => 2, 'city_id' => 27]);
        Main_Division::create(['id' => 127, 'name' => 'МБУ ЦСО Яйского МО', 'type_id' => 2, 'city_id' => 28]);
        Main_Division::create(['id' => 128, 'name' => 'МКУ СРЦ для несовершеннолетних', 'type_id' => 2, 'city_id' => 28]);
        Main_Division::create(['id' => 129, 'name' => 'МКУ СРЦдН', 'type_id' => 2, 'city_id' => 29]);
        Main_Division::create(['id' => 130, 'name' => 'МКУ ЦСО', 'type_id' => 2, 'city_id' => 29]);
        Main_Division::create(['id' => 131, 'name' => 'Заводский отдел СЗН администрации г.Кемерово', 'type_id' => 2, 'city_id' => 7]);
        Main_Division::create(['id' => 132, 'name' => 'Кировский отдел СЗН Администрации г. Кемерово', 'type_id' => 2, 'city_id' => 7]);
        Main_Division::create(['id' => 133, 'name' => 'КСП администрации Новокузнецкого МО', 'type_id' => 1, 'city_id' => 16]);
        Main_Division::create(['id' => 134, 'name' => 'КСЗН администрации Топкинского МО', 'type_id' => 1, 'city_id' => 24]);
        Main_Division::create(['id' => 135, 'name' => 'КСЗН Беловского ГО', 'type_id' => 1, 'city_id' => 2]);
        Main_Division::create(['id' => 136, 'name' => 'Ленинский отдел СЗН Администрации г. Кемерово', 'type_id' => 2, 'city_id' => 7]);
        Main_Division::create(['id' => 137, 'name' => 'Рудничный отдел СЗН', 'type_id' => 2, 'city_id' => 19]);
        Main_Division::create(['id' => 138, 'name' => 'Рудничный отдел СЗН администрации', 'type_id' => 2, 'city_id' => 7]);
        Main_Division::create(['id' => 139, 'name' => 'УСЗН Прокопьевского района (Красный брод)', 'type_id' => 1, 'city_id' => 19]);
        Main_Division::create(['id' => 140, 'name' => 'УСЗН администрации Анжеро-Судженского ГО', 'type_id' => 1, 'city_id' => 1]);
        Main_Division::create(['id' => 141, 'name' => 'УСЗН администрации Беловского МО', 'type_id' => 1, 'city_id' => 2]);
        Main_Division::create(['id' => 142, 'name' => 'УСЗН Администрации города Юрги', 'type_id' => 1, 'city_id' => 27]);
        Main_Division::create(['id' => 143, 'name' => 'УСЗН администрации Гурьевского МО', 'type_id' => 1, 'city_id' => 4]);
        Main_Division::create(['id' => 144, 'name' => 'УСЗН Администрации Калтанского ГО', 'type_id' => 1, 'city_id' => 6]);
        Main_Division::create(['id' => 145, 'name' => 'УСЗН администрации Кемеровского МО', 'type_id' => 1, 'city_id' => 7]);
        Main_Division::create(['id' => 146, 'name' => 'УСЗН администрации Крапивинского МО', 'type_id' => 1, 'city_id' => 10]);
        Main_Division::create(['id' => 147, 'name' => 'УСЗН администрации Ленинск-Кузнецкого ГО', 'type_id' => 1, 'city_id' => 12]);
        Main_Division::create(['id' => 148, 'name' => 'УСЗН администрации Ленинск-Кузнецкого МО', 'type_id' => 1, 'city_id' => 12]);
        Main_Division::create(['id' => 149, 'name' => 'УСЗН администрации Мариинского МО', 'type_id' => 1, 'city_id' => 13]);
        Main_Division::create(['id' => 150, 'name' => 'УСЗН администрации Междуреченского ГО', 'type_id' => 1, 'city_id' => 14]);
        Main_Division::create(['id' => 151, 'name' => 'УСЗН администрации Осинниковского ГО', 'type_id' => 1, 'city_id' => 17]);
        Main_Division::create(['id' => 152, 'name' => 'УСЗН администрации Прокопьевского МО', 'type_id' => 1, 'city_id' => 19]);
        Main_Division::create(['id' => 153, 'name' => 'УСЗН администрации Промышленновского МО', 'type_id' => 1, 'city_id' => 20]);
        Main_Division::create(['id' => 154, 'name' => 'УСЗН администрации Тайгинского ГО', 'type_id' => 1, 'city_id' => 21]);
        Main_Division::create(['id' => 155, 'name' => 'УСЗН администрации Таштагольского МО', 'type_id' => 1, 'city_id' => 22]);
        Main_Division::create(['id' => 156, 'name' => 'УСЗН администрации Тисульского МО', 'type_id' => 1, 'city_id' => 23]);
        Main_Division::create(['id' => 157, 'name' => 'УСЗН администрации Тяжинского МО', 'type_id' => 1, 'city_id' => 25]);
        Main_Division::create(['id' => 158, 'name' => 'УСЗН администрации Юргинского МО', 'type_id' => 1, 'city_id' => 27]);
        Main_Division::create(['id' => 159, 'name' => 'УСЗН администрации Яшкинского МО', 'type_id' => 1, 'city_id' => 29]);
        Main_Division::create(['id' => 160, 'name' => 'УСЗН Березовского ГО', 'type_id' => 1, 'city_id' => 3]);
        Main_Division::create(['id' => 161, 'name' => 'УСЗН Заводского района г.Новокузнецка', 'type_id' => 1, 'city_id' => 16]);
        Main_Division::create(['id' => 162, 'name' => 'УСЗН Ижморского МО', 'type_id' => 1, 'city_id' => 5]);
        Main_Division::create(['id' => 163, 'name' => 'УСЗН Киселевского ГО', 'type_id' => 1, 'city_id' => 9]);
        Main_Division::create(['id' => 164, 'name' => 'УСЗН Кузнецкого района г.Новокузнецка', 'type_id' => 1, 'city_id' => 16]);
        Main_Division::create(['id' => 165, 'name' => 'УСЗН Куйбышевского района г.Новокузнецка', 'type_id' => 1, 'city_id' => 16]);
        Main_Division::create(['id' => 166, 'name' => 'УСЗН Мысковского ГО', 'type_id' => 1, 'city_id' => 15]);
        Main_Division::create(['id' => 167, 'name' => 'УСЗН Новоильинского района г.Новокузнецка', 'type_id' => 1, 'city_id' => 16]);
        Main_Division::create(['id' => 168, 'name' => 'УСЗН Орджоникидзевского района г.Новокузнецка', 'type_id' => 1, 'city_id' => 16]);
        Main_Division::create(['id' => 169, 'name' => 'УСЗН Полысаевского ГО', 'type_id' => 1, 'city_id' => 18]);
        Main_Division::create(['id' => 170, 'name' => 'УСЗН Центрального района г.Новокузнецка', 'type_id' => 1, 'city_id' => 16]);
        Main_Division::create(['id' => 171, 'name' => 'УСЗН Чебулинского МО', 'type_id' => 1, 'city_id' => 26]);
        Main_Division::create(['id' => 172, 'name' => 'УСЗН Яйского МО', 'type_id' => 1, 'city_id' => 28]);
        Main_Division::create(['id' => 173, 'name' => 'Центральный отдел СЗН г. Прокопьевска', 'type_id' => 2, 'city_id' => 19]);
        Main_Division::create(['id' => 174, 'name' => 'Центральный район СЗН администрации города Кемерово', 'type_id' => 2, 'city_id' => 7]);
        Main_Division::create(['id' => 175, 'name' => 'УСЗН администрации г. Кемерово', 'type_id' => 1, 'city_id' => 7]);
        Main_Division::create(['id' => 176, 'name' => 'Зенковский отдел СЗН г. Прокопьевска', 'type_id' => 2, 'city_id' => 19]);
        Main_Division::create(['id' => 177, 'name' => 'КСЗН г. Прокопьевска', 'type_id' => 1, 'city_id' => 19]);
        Main_Division::create(['id' => 178, 'name' => 'КСЗН г. Новокузнецк', 'type_id' => 1, 'city_id' => 16]);
        Main_Division::create(['id' => 179, 'name' => 'ГБУ "Междуреченский дом-интернат для престарелых и инвалидов"', 'type_id' => 2, 'city_id' => 14]);
        Main_Division::create(['id' => 180, 'name' => 'ГБУ "Анжеро-Судженский дом-интернат для престарелых и инвалидов"', 'type_id' => 2, 'city_id' => 1]);
        Main_Division::create(['id' => 181, 'name' => 'ГАУ Санаторий "Борисовский"', 'type_id' => 2, 'city_id' => 10]);
        Main_Division::create(['id' => 182, 'name' => 'ГБУ Прокопьевский реабилитационный центр «Радуга»', 'type_id' => 2, 'city_id' => 19]);
        Main_Division::create(['id' => 183, 'name' => 'ГКУ "Государственное юридическое бюро Кузбасса"', 'type_id' => 2, 'city_id' => 7]);
        Main_Division::create(['id' => 184, 'name' => 'МКУ "Центр организации соц. обслуживания г. Кемерово" ', 'type_id' => 2, 'city_id' => 7]);
        Main_Division::create(['id' => 185, 'name' => 'МБУ КЦСОН Заводского района г. Новокузнецк', 'type_id' => 2, 'city_id' => 16]);
    }
}
