<?php

namespace Database\Seeders\Main;

use App\Models\Main\City;
use App\Models\Main\Division;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DivisionSeeder extends Seeder
{
    public function run(): void
    {
        City::create(['code' => 'anj-sudj',     'name' => 'Анжеро-Судженск']);
        City::create(['code' => 'belovo',       'name' => 'Белово']);
        City::create(['code' => 'berez',        'name' => 'Берёзовский']);
        City::create(['code' => 'gur',          'name' => 'Гурьевск']);
        City::create(['code' => 'ijm',          'name' => 'Ижморский']);
        City::create(['code' => 'kaltan',       'name' => 'Калтан']);
        City::create(['code' => 'kem',          'name' => 'Кемерово']);
        City::create(['code' => 'kisel',        'name' => 'Киселёвск']);
        City::create(['code' => 'krapiv',       'name' => 'Крапивинский']);
        City::create(['code' => 'lk-kuz',       'name' => 'Ленинск-Кузнецкий']);
        City::create(['code' => 'mariinsk',     'name' => 'Мариинск']);
        City::create(['code' => 'mejd',         'name' => 'Междуреченск']);
        City::create(['code' => 'myski',        'name' => 'Мыски']);
        City::create(['code' => 'nk',           'name' => 'Новокузнецк']);
        City::create(['code' => 'osin',         'name' => 'Осинники']);
        City::create(['code' => 'prokop',       'name' => 'Прокопьевск']);
        City::create(['code' => 'promish',      'name' => 'Промышленовский']);
        City::create(['code' => 'tayga',        'name' => 'Тайга']);
        City::create(['code' => 'tashtag',      'name' => 'Таштагол']);
        City::create(['code' => 'tisul',        'name' => 'Тисуль']);
        City::create(['code' => 'topki',        'name' => 'Топки']);
        City::create(['code' => 'tyajin',       'name' => 'Тяжин']);
        City::create(['code' => 'cheb',         'name' => 'Чебула']);
        City::create(['code' => 'yrga',         'name' => 'Юрга']);
        City::create(['code' => 'yaya',         'name' => 'Яя']);
        City::create(['code' => 'yash',         'name' => 'Яшкино']);

        Division::create(['name' => 'МТСЗН Кузбасса',                                                                                                                       'city_code' => 'kem']);
        Division::create(['name' => 'ГКУ ЦСВИ',                                                                                                                             'city_code' => 'kem']);
        Division::create(['name' => 'ГАУ Журавлевский дом-интернат для престарелых и инвалидов',                                                                            'city_code' => 'kem']);
        Division::create(['name' => 'МКУ ЦСО ГПВиИ г. Таштагол',                                                                                                            'city_code' => 'tashtag']);
        Division::create(['name' => 'АНО "Жизнь"',                                                                                                                          'city_code' => 'anj-sudj']);
        Division::create(['name' => 'БФ "Загадай желание"',                                                                                                                 'city_code' => 'anj-sudj']);
        Division::create(['name' => 'ГБУ "Анжеро-Судженский дом-интернат для граждан, имеющих психические расстройства"',                                                   'city_code' => 'anj-sudj']);
        Division::create(['name' => 'МБУ "Анжеро-Судженский КЦСОН"',                                                                                                        'city_code' => 'anj-sudj']);
        Division::create(['name' => 'МКУ "Реабилитационный центр" г. Анжеро-Судженск',                                                                                      'city_code' => 'anj-sudj']);
        Division::create(['name' => 'МКУ СРЦ для несовершеннолетних г. Анжеро-Судженск',                                                                                    'city_code' => 'anj-sudj']);
        Division::create(['name' => 'ГБУ "Евтинский ДДИ для детей с ментальными нарушениями"',                                                                              'city_code' => 'belovo']);
        Division::create(['name' => 'ГБУ "Инской дом-интернат для граждан, имеющих психические расстройства"',                                                              'city_code' => 'belovo']);
        Division::create(['name' => 'МБУ ЦСО г. Белово',                                                                                                                    'city_code' => 'belovo']);
        Division::create(['name' => 'МКУ ЦСОН г. Белово',                                                                                                                   'city_code' => 'belovo']);
        Division::create(['name' => 'МКУ СРЦ "Теплый дом"',                                                                                                                 'city_code' => 'belovo']);
        Division::create(['name' => 'МКУ ЦСПСиД г.Белово',                                                                                                                  'city_code' => 'belovo']);
        Division::create(['name' => 'ООО "Чибисы"',                                                                                                                         'city_code' => 'belovo']);
        Division::create(['name' => 'МБУ ЦСО Березовского ГО',                                                                                                              'city_code' => 'berez']);
        Division::create(['name' => 'МКУ СРЦ "Берегиня"',                                                                                                                   'city_code' => 'berez']);
        Division::create(['name' => 'ГКУ "Гурьевский дом-интернат для граждан, имеющих психические расстройства"',                                                          'city_code' => 'gur']);
        Division::create(['name' => 'МКУ СРЦ для несовершеннолетних" г. Гурьевск',                                                                                          'city_code' => 'gur']);
        Division::create(['name' => 'МКУ ЦСО г. Гурьевск',                                                                                                                  'city_code' => 'gur']);
        Division::create(['name' => 'МБУ КЦСОН Ижморский МР',                                                                                                               'city_code' => 'ijm']);
        Division::create(['name' => 'АНО "Центр Социального Развития" г. Калтан',                                                                                           'city_code' => 'kaltan']);
        Division::create(['name' => 'ГБУ "Малиновский дом-интернат для граждан, имеющих психические расстройства"',                                                         'city_code' => 'kaltan']);
        Division::create(['name' => 'МКУ ЦСО Калтанского ГО',                                                                                                               'city_code' => 'kaltan']);
        Division::create(['name' => 'МКУ ЦСПСД г. Калтан',                                                                                                                  'city_code' => 'kaltan']);
        Division::create(['name' => 'АНО "Православная патронажная служба"',                                                                                                'city_code' => 'kem']);
        Division::create(['name' => 'АНО пансионат по уходу за пожилыми иинвалидами "ВероНика"',                                                                            'city_code' => 'kem']);
        Division::create(['name' => 'АНО Психологический центр "СемьЯ"',                                                                                                    'city_code' => 'kem']);
        Division::create(['name' => 'АНО Дом-интернат для престарелых и инвалидов "Семеновна"',                                                                             'city_code' => 'kem']);
        Division::create(['name' => 'АНО Пансионат для пожилых людей "Доброе сердце"',                                                                                      'city_code' => 'kem']);
        Division::create(['name' => 'АНО "Социальный скреп"',                                                                                                               'city_code' => 'kem']);
        Division::create(['name' => 'АНО "ВОСХОЖДЕНИЕ"',                                                                                                                    'city_code' => 'kem']);
        Division::create(['name' => 'ГАУ "Кемеровский дом-интернат для престарелых и инвалидов"',                                                                           'city_code' => 'kem']);
        Division::create(['name' => 'ГАУ "Кемеровский центр социальной адаптации населения"',                                                                               'city_code' => 'kem']);
        Division::create(['name' => 'ГБУ "Кедровский дом-интернат для граждан, имеющих психические расстройства"',                                                          'city_code' => 'kem']);
        Division::create(['name' => 'ГКУ СРЦ для несовершеннолетних "Маленький принц"',                                                                                     'city_code' => 'kem']);
        Division::create(['name' => 'ГАУ "Фламинго"',                                                                                                                       'city_code' => 'kem']);
        Division::create(['name' => 'КГОО "Интеграция"',                                                                                                                    'city_code' => 'kem']);
        Division::create(['name' => 'МАУ "КЦСОН Кировского района г. Кемерово"',                                                                                            'city_code' => 'kem']);
        Division::create(['name' => 'МБУ "КЦСОН ж.р.Кедровка г.Кемерово"',                                                                                                  'city_code' => 'kem']);
        Division::create(['name' => 'МБУ "КЦСОН Заводского района г. Кемерово"',                                                                                            'city_code' => 'kem']);
        Division::create(['name' => 'МБУ "КЦСОН Ленинского района г. Кемерово"',                                                                                            'city_code' => 'kem']);
        Division::create(['name' => 'МБУ "КЦСОН Рудничного района г. Кемерово"',                                                                                            'city_code' => 'kem']);
        Division::create(['name' => 'МБУ "КЦСОН Центрального района г. Кемерово"',                                                                                          'city_code' => 'kem']);
        Division::create(['name' => 'МКУ "КЦСОН Кемеровского МО"',                                                                                                          'city_code' => 'kem']);
        Division::create(['name' => 'МКУ ЦСПСиД г. Кемерово',                                                                                                               'city_code' => 'kem']);
        Division::create(['name' => 'НКО КРОО "Новые горизонты"',                                                                                                           'city_code' => 'kem']);
        Division::create(['name' => 'ООО "Гармония"',                                                                                                                       'city_code' => 'kem']);
        Division::create(['name' => 'РОО ООО "Всероссийское ордена Трудового Красного Знамени общество слепых"',                                                            'city_code' => 'kem']);
        Division::create(['name' => 'МКУ ЦСО г. Киселевск',                                                                                                                 'city_code' => 'kisel']);
        Division::create(['name' => 'МКУ СРЦ "Доверие"',                                                                                                                    'city_code' => 'kisel']);
        Division::create(['name' => 'МБУ КЦСОН Крапивинского МО',                                                                                                           'city_code' => 'krapiv']);
        Division::create(['name' => 'МКУ СРЦ для несовершеннолетних пгт. Крапивинский',                                                                                     'city_code' => 'krapiv']);
        Division::create(['name' => 'ООО "Ренессанс"',                                                                                                                      'city_code' => 'krapiv']);
        Division::create(['name' => 'ГБУ "Краснинский дом-интернат для граждан, имеющих психические расстройства"',                                                         'city_code' => 'lk-kuz']);
        Division::create(['name' => 'ГБУ "Ленинск-Кузнецкий реабилитационный центр для детей и подростков с ограниченными возможностями"',                                  'city_code' => 'lk-kuz']);
        Division::create(['name' => 'МБУ ЦСОН г.Ленинск-Кузнецкий',                                                                                                         'city_code' => 'lk-kuz']);
        Division::create(['name' => 'МКУ СРЦ "Надежда"',                                                                                                                    'city_code' => 'lk-kuz']);
        Division::create(['name' => 'МКУ СРЦ "Радуга"',                                                                                                                     'city_code' => 'lk-kuz']);
        Division::create(['name' => 'МКУ ЦСО ГПВИИ г. Ленинск-Кузнецкий',                                                                                                   'city_code' => 'lk-kuz']);
        Division::create(['name' => 'АНО Центр Социальной Помощи "Гавань Надежды"',                                                                                         'city_code' => 'mariinsk']);
        Division::create(['name' => 'ГБУ "Благовещенский дом-интернат для граждан, имеющих психические расстройства"',                                                      'city_code' => 'mariinsk']);
        Division::create(['name' => 'ГБУ "Мариинский дом-интернат для граждан, имеющих психические расстройства"',                                                          'city_code' => 'mariinsk']);
        Division::create(['name' => 'ГБУ "Мариинский реабилитационный центр для детей и подростков с ограниченными возможностями"',                                         'city_code' => 'mariinsk']);
        Division::create(['name' => 'МБУ КЦСОН Мариинского МР',                                                                                                             'city_code' => 'mariinsk']);
        Division::create(['name' => 'МКУ СРЦ для несовершеннолетних" г. Мариинск',                                                                                          'city_code' => 'mariinsk']);
        Division::create(['name' => 'ГБУ "Междуреченский дом-интернат для граждан, имеющих психические расстройства"',                                                      'city_code' => 'mejd']);
        Division::create(['name' => 'МБУ КЦСОН г.Междуреченск',                                                                                                             'city_code' => 'mejd']);
        Division::create(['name' => 'МКУ СРЦ для несовершеннолетних г. Междуреченск',                                                                                       'city_code' => 'mejd']);
        Division::create(['name' => 'МКУ ЦСПСиД г. Междуреченск',                                                                                                           'city_code' => 'mejd']);
        Division::create(['name' => 'ГБУ "Мысковский ДДИ для детей с ментальными нарушениями"',                                                                             'city_code' => 'myski']);
        Division::create(['name' => 'МКУ СРЦ для несовершеннолетних г. Мыски',                                                                                              'city_code' => 'myski']);
        Division::create(['name' => 'МКУ ЦСОН г. Мыски',                                                                                                                    'city_code' => 'myski']);
        Division::create(['name' => 'БФ "Источник жизни"',                                                                                                                  'city_code' => 'nk']);
        Division::create(['name' => 'ГКУ "Новокузнецкий дом-интернат для престарелых и инвалидов"',                                                                         'city_code' => 'nk']);
        Division::create(['name' => 'МБУ КЦСОН Кузнецкого района г. Новокузнецк',                                                                                           'city_code' => 'nk']);
        Division::create(['name' => 'МБУ КЦСОН Куйбышевского района г. Новокузнецк',                                                                                        'city_code' => 'nk']);
        Division::create(['name' => 'МБУ КЦСОН Новоильинского района г. Новокузнецк',                                                                                       'city_code' => 'nk']);
        Division::create(['name' => 'МБУ КЦСОН Орджоникидзевского района г. Новокузнецк',                                                                                   'city_code' => 'nk']);
        Division::create(['name' => 'МБУ КЦСОН Центрального района г. Новокузнецк',                                                                                         'city_code' => 'nk']);
        Division::create(['name' => 'МКУ Дом ночного пребывания для лиц без определенного места жительства и занятий',                                                      'city_code' => 'nk']);
        Division::create(['name' => 'МКУ КЦСОН МО "НМО Кемеровской области-Кузбасса"',                                                                                      'city_code' => 'nk']);
        Division::create(['name' => 'МКУ СРЦ "Алые паруса"',                                                                                                                'city_code' => 'nk']);
        Division::create(['name' => 'МКУ СРЦ "Полярная звезда"',                                                                                                            'city_code' => 'nk']);
        Division::create(['name' => 'МКУ СРЦ "Уютный дом"',                                                                                                                 'city_code' => 'nk']);
        Division::create(['name' => 'МКУ ЦСПСиД г. Новокузнецк',                                                                                                            'city_code' => 'nk']);
        Division::create(['name' => 'МКУ ЦСПСиД "Виктория""',                                                                                                               'city_code' => 'nk']);
        Division::create(['name' => 'МКУ Центр реабилитации детей и подростков сограниченными возможностями г. Новокузнецк',                                                'city_code' => 'nk']);
        Division::create(['name' => 'ООО "Росток"',                                                                                                                         'city_code' => 'nk']);
        Division::create(['name' => 'ООО "Здоровье"',                                                                                                                       'city_code' => 'nk']);
        Division::create(['name' => 'ООО "Здоровье-НК"',                                                                                                                    'city_code' => 'nk']);
        Division::create(['name' => 'МБУ ЦСО Осиниковского ГО',                                                                                                             'city_code' => 'osin']);
        Division::create(['name' => 'МКУ ЦСПСиД г. Осиники',                                                                                                                'city_code' => 'osin']);
        Division::create(['name' => 'МБУ КЦСОН г. Полысаево',                                                                                                               'city_code' => 'lk-kuz']);
        Division::create(['name' => 'ГБУ "Прокопьевский дом-интернат для граждан, имеющих психические расстройства"',                                                       'city_code' => 'prokop']);
        Division::create(['name' => 'КРООБН "Дом свободы"',                                                                                                                 'city_code' => 'prokop']);
        Division::create(['name' => 'МБУ ЦСОН г. Прокопьевск',                                                                                                              'city_code' => 'prokop']);
        Division::create(['name' => 'МКУ СРЦ для несовершеннолетних "Алиса"',                                                                                               'city_code' => 'prokop']);
        Division::create(['name' => 'МКУ ЦОСО г. Прокопьевск',                                                                                                              'city_code' => 'prokop']);
        Division::create(['name' => 'МКУ ЦСО г. Прокопьевск',                                                                                                               'city_code' => 'prokop']);
        Division::create(['name' => 'МКУ СРЦ для несовершеннолетних г. Прокопьевск',                                                                                        'city_code' => 'prokop']);
        Division::create(['name' => 'МБУ КЦСОН Промышленновского МО',                                                                                                       'city_code' => 'promish']);
        Division::create(['name' => 'ГБУ "Тайгинский дом-интернат для граждан, имеющих психические расстройства"',                                                          'city_code' => 'tayga']);
        Division::create(['name' => 'МБУ КЦСОН Тяжинского ГО',                                                                                                              'city_code' => 'tayga']);
        Division::create(['name' => 'МКУ СРЦ для несовершеннолетних" г. Тайга',                                                                                             'city_code' => 'tayga']);
        Division::create(['name' => 'МКУ СРЦ для несовершеннолетних г. Таштагол',                                                                                           'city_code' => 'tashtag']);
        Division::create(['name' => 'ГБУ "Листвянский дом-интернат для граждан, имеющих психические расстройства"',                                                         'city_code' => 'tisul']);
        Division::create(['name' => 'МКУ СРЦ пгт. Тисуль',                                                                                                                  'city_code' => 'tisul']);
        Division::create(['name' => 'МКУ ЦСО пгт. Тисуль',                                                                                                                  'city_code' => 'tisul']);
        Division::create(['name' => 'МБУ ЦСО г. Топки',                                                                                                                     'city_code' => 'topki']);
        Division::create(['name' => 'МКУ СРЦ "Центр Семья"',                                                                                                                'city_code' => 'topki']);
        Division::create(['name' => 'ГКУ "Кубитетский специальный дом-интернат для престарелых и инвалидов"',                                                               'city_code' => 'tyajin']);
        Division::create(['name' => 'МБУ ЦСОН Тяжинского МО',                                                                                                               'city_code' => 'tyajin']);
        Division::create(['name' => 'МКУ СРЦ для несовершеннолетних" пгт. Тяжинский',                                                                                       'city_code' => 'tyajin']);
        Division::create(['name' => 'МКУ КЦСОН Чебулинского МО',                                                                                                            'city_code' => 'cheb']);
        Division::create(['name' => 'ГАУ "Юргинский дом-интернат для граждан, имеющих психические расстройства"',                                                           'city_code' => 'yrga']);
        Division::create(['name' => 'ГАУ "Юргинский дом-интернат для престарелых и инвалидов"',                                                                             'city_code' => 'yrga']);
        Division::create(['name' => 'ГБУ "Юргинский ДДИ для детей с ментальными нарушениями"',                                                                              'city_code' => 'yrga']);
        Division::create(['name' => 'МБУ "ЦСО ГПВиИ г. Юрги"',                                                                                                              'city_code' => 'yrga']);
        Division::create(['name' => 'МКУ "КЦСОН Юргинского МО"',                                                                                                            'city_code' => 'yrga']);
        Division::create(['name' => 'МКУ СРЦ для несовершеннолетних "Солнышко"',                                                                                            'city_code' => 'yrga']);
        Division::create(['name' => 'МКУ ЦСПСиД г. Юрга',                                                                                                                   'city_code' => 'yrga']);
        Division::create(['name' => 'МБУ ЦСО Яйского МО',                                                                                                                   'city_code' => 'yaya']);
        Division::create(['name' => 'МКУ СРЦ для несовершеннолетних пгт. Яя',                                                                                               'city_code' => 'yaya']);
        Division::create(['name' => 'МКУ СРЦдН пгт. Яшкино',                                                                                                                'city_code' => 'yash']);
        Division::create(['name' => 'МКУ ЦСО пгт. Яшкино',                                                                                                                  'city_code' => 'yash']);
        Division::create(['name' => 'Заводский отдел СЗН администрации г.Кемерово',                                                                                         'city_code' => 'kem']);
        Division::create(['name' => 'Кировский отдел СЗН Администрации г. Кемерово',                                                                                        'city_code' => 'kem']);
        Division::create(['name' => 'КСП администрации Новокузнецкого МО',                                                                                                  'city_code' => 'nk']);
        Division::create(['name' => 'КСЗН администрации Топкинского МО',                                                                                                    'city_code' => 'topki']);
        Division::create(['name' => 'КСЗН Беловского ГО',                                                                                                                   'city_code' => 'belovo']);
        Division::create(['name' => 'Ленинский отдел СЗН Администрации г. Кемерово',                                                                                        'city_code' => 'kem']);
        Division::create(['name' => 'Рудничный отдел СЗН Администрации г. Кемерово',                                                                                        'city_code' => 'prokop']);
        Division::create(['name' => 'Рудничный отдел СЗН администрации',                                                                                                    'city_code' => 'kem']);
        Division::create(['name' => 'УСЗН Прокопьевского района (Красный брод)',                                                                                            'city_code' => 'prokop']);
        Division::create(['name' => 'УСЗН администрации Анжеро-Судженского ГО',                                                                                             'city_code' => 'anj-sudj']);
        Division::create(['name' => 'УСЗН администрации Беловского МО',                                                                                                     'city_code' => 'belovo']);
        Division::create(['name' => 'УСЗН Администрации г. Юрги',                                                                                                           'city_code' => 'yrga']);
        Division::create(['name' => 'УСЗН администрации Гурьевского МО',                                                                                                    'city_code' => 'gur']);
        Division::create(['name' => 'УСЗН Администрации Калтанского ГО',                                                                                                    'city_code' => 'kaltan']);
        Division::create(['name' => 'УСЗН администрации Кемеровского МО',                                                                                                   'city_code' => 'kem']);
        Division::create(['name' => 'УСЗН администрации Крапивинского МО',                                                                                                  'city_code' => 'krapiv']);
        Division::create(['name' => 'УСЗН администрации Ленинск-Кузнецкого ГО',                                                                                             'city_code' => 'lk-kuz']);
        Division::create(['name' => 'УСЗН администрации Ленинск-Кузнецкого МО',                                                                                             'city_code' => 'lk-kuz']);
        Division::create(['name' => 'УСЗН администрации Мариинского МО',                                                                                                    'city_code' => 'mariinsk']);
        Division::create(['name' => 'УСЗН администрации Междуреченского ГО',                                                                                                'city_code' => 'mejd']);
        Division::create(['name' => 'УСЗН администрации Осинниковского ГО',                                                                                                 'city_code' => 'osin']);
        Division::create(['name' => 'УСЗН администрации Прокопьевского МО',                                                                                                 'city_code' => 'prokop']);
        Division::create(['name' => 'УСЗН администрации Промышленновского МО',                                                                                              'city_code' => 'promish']);
        Division::create(['name' => 'УСЗН администрации Тайгинского ГО',                                                                                                    'city_code' => 'tayga']);
        Division::create(['name' => 'УСЗН администрации Таштагольского МО',                                                                                                 'city_code' => 'tashtag']);
        Division::create(['name' => 'УСЗН администрации Тисульского МО',                                                                                                    'city_code' => 'tisul']);
        Division::create(['name' => 'УСЗН администрации Тяжинского МО',                                                                                                     'city_code' => 'tyajin']);
        Division::create(['name' => 'УСЗН администрации Юргинского МО',                                                                                                     'city_code' => 'yrga']);
        Division::create(['name' => 'УСЗН администрации Яшкинского МО',                                                                                                     'city_code' => 'yash']);
        Division::create(['name' => 'УСЗН Березовского ГО',                                                                                                                 'city_code' => 'berez']);
        Division::create(['name' => 'УСЗН Заводского района г.Новокузнецка',                                                                                                'city_code' => 'nk']);
        Division::create(['name' => 'УСЗН Ижморского МО',                                                                                                                   'city_code' => 'ijm']);
        Division::create(['name' => 'УСЗН Киселевского ГО',                                                                                                                 'city_code' => 'kisel']);
        Division::create(['name' => 'УСЗН Кузнецкого района г.Новокузнецка',                                                                                                'city_code' => 'nk']);
        Division::create(['name' => 'УСЗН Куйбышевского района г.Новокузнецка',                                                                                             'city_code' => 'nk']);
        Division::create(['name' => 'УСЗН Мысковского ГО',                                                                                                                  'city_code' => 'myski']);
        Division::create(['name' => 'УСЗН Новоильинского района г.Новокузнецка',                                                                                            'city_code' => 'nk']);
        Division::create(['name' => 'УСЗН Орджоникидзевского района г.Новокузнецка',                                                                                        'city_code' => 'nk']);
        Division::create(['name' => 'УСЗН Центрального района г.Новокузнецка',                                                                                              'city_code' => 'nk']);
        Division::create(['name' => 'УСЗН Чебулинского МО',                                                                                                                 'city_code' => 'cheb']);
        Division::create(['name' => 'УСЗН Яйского МО',                                                                                                                      'city_code' => 'yaya']);
        Division::create(['name' => 'Центральный отдел СЗН г. Прокопьевска',                                                                                                'city_code' => 'prokop']);
        Division::create(['name' => 'УСЗН администрации г. Кемерово',                                                                                                       'city_code' => 'kem']);
        Division::create(['name' => 'Зенковский отдел СЗН г. Прокопьевска',                                                                                                 'city_code' => 'prokop']);
        Division::create(['name' => 'КСЗН г. Прокопьевска',                                                                                                                 'city_code' => 'prokop']);
        Division::create(['name' => 'КСЗН г. Новокузнецк',                                                                                                                  'city_code' => 'nk']);
        Division::create(['name' => 'ГБУ "Междуреченский дом-интернат для престарелых и инвалидов"',                                                                        'city_code' => 'mejd']);
        Division::create(['name' => 'ГБУ "Анжеро-Судженский дом-интернат для престарелых и инвалидов"',                                                                     'city_code' => 'anj-sudj']);
        Division::create(['name' => 'ГАУ Санаторий "Борисовский"',                                                                                                          'city_code' => 'krapiv']);
        Division::create(['name' => 'ГБУ Прокопьевский реабилитационный центр «Радуга»',                                                                                    'city_code' => 'prokop']);
        Division::create(['name' => 'ГКУ "Государственное юридическое бюро Кузбасса"',                                                                                      'city_code' => 'kem']);
        Division::create(['name' => 'МКУ "Центр организации соц. обслуживания г. Кемерово" ',                                                                               'city_code' => 'kem']);
        Division::create(['name' => 'МБУ КЦСОН Заводского района г. Новокузнецк',                                                                                           'city_code' => 'nk']);
        Division::create(['name' => 'Разработчики',                                                                                                                         'city_code' => null]);
        Division::create(['name' => 'Центральный отдел СЗН администрации г.Кемерово',                                                                                       'city_code' => 'kem']);
    }
}
