<?php

namespace Database\Seeders\CSVI;

use App\Models\CSVI\Technical\Mark;
use App\Models\CSVI\Technical\Type;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TechnicalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Type::create(['id' => 1, 'name' => 'АРМ']);
        Type::create(['id' => 2, 'name' => 'МФУ']);
        Type::create(['id' => 3, 'name' => 'Ноутбук']);
        Type::create(['id' => 4, 'name' => 'Принтер']);
        Type::create(['id' => 5, 'name' => 'Сервер']);
        Type::create(['id' => 7, 'name' => 'Системный блок']);
        Type::create(['id' => 8, 'name' => 'Монитор']);
        Type::create(['id' => 9, 'name' => 'Моноблок']);
        Type::create(['id' => 10, 'name' => 'Копировальный аппарат']);
        Type::create(['id' => 11, 'name' => 'Планшет']);

        Mark::create(['id' => 2, 'type_id' => 1, 'name' => 'Depo']);
        Mark::create(['id' => 3, 'type_id' => 1, 'name' => 'ICL']);
        Mark::create(['id' => 4, 'type_id' => 1, 'name' => 'Аквариус']);
        Mark::create(['id' => 5, 'type_id' => 1, 'name' => 'kraftway']);
        Mark::create(['id' => 6, 'type_id' => 1, 'name' => 'Lenovo']);
        Mark::create(['id' => 7, 'type_id' => 1, 'name' => 'RAMEC']);
        Mark::create(['id' => 8, 'type_id' => 1, 'name' => 'OLDI']);
        Mark::create(['id' => 9, 'type_id' => 1, 'name' => 'НЭТА']);
        Mark::create(['id' => 10, 'type_id' => 1, 'name' => 'VELTON']);
        Mark::create(['id' => 11, 'type_id' => 1, 'name' => 'Intel']);
        Mark::create(['id' => 12, 'type_id' => 1, 'name' => 'AMD']);
        Mark::create(['id' => 13, 'type_id' => 1, 'name' => 'NPC']);
        Mark::create(['id' => 14, 'type_id' => 1, 'name' => 'GigaBayte']);
        Mark::create(['id' => 15, 'type_id' => 1, 'name' => '3Logic']);
        Mark::create(['id' => 16, 'type_id' => 1, 'name' => 'Acer']);
        Mark::create(['id' => 17, 'type_id' => 1, 'name' => 'Credo']);
        Mark::create(['id' => 18, 'type_id' => 1, 'name' => 'RAI']);
        Mark::create(['id' => 19, 'type_id' => 1, 'name' => 'R-Style']);
        Mark::create(['id' => 20, 'type_id' => 1, 'name' => 'ASUS']);
        Mark::create(['id' => 21, 'type_id' => 1, 'name' => 'DEXP']);
        Mark::create(['id' => 22, 'type_id' => 1, 'name' => 'RAY']);
        Mark::create(['id' => 23, 'type_id' => 1, 'name' => 'InWin']);
        Mark::create(['id' => 24, 'type_id' => 1, 'name' => 'ExeGate']);
        Mark::create(['id' => 25, 'type_id' => 1, 'name' => 'BRIGHTWINS']);
        Mark::create(['id' => 26, 'type_id' => 1, 'name' => 'MAGELAN']);
        Mark::create(['id' => 27, 'type_id' => 1, 'name' => 'AeroCool']);
        Mark::create(['id' => 28, 'type_id' => 1, 'name' => 'Krauler']);
        Mark::create(['id' => 29, 'type_id' => 1, 'name' => 'CHUWI']);
        Mark::create(['id' => 30, 'type_id' => 1, 'name' => 'AOC']);
        Mark::create(['id' => 31, 'type_id' => 1, 'name' => 'DNS']);
        Mark::create(['id' => 32, 'type_id' => 1, 'name' => 'BENQ']);
        Mark::create(['id' => 33, 'type_id' => 1, 'name' => 'Samsung']);
        Mark::create(['id' => 34, 'type_id' => 1, 'name' => 'LG']);
        Mark::create(['id' => 35, 'type_id' => 2, 'name' => 'Pantum']);
        Mark::create(['id' => 36, 'type_id' => 2, 'name' => 'Samsung']);
        Mark::create(['id' => 37, 'type_id' => 2, 'name' => 'HP']);
        Mark::create(['id' => 38, 'type_id' => 2, 'name' => 'Canon']);
        Mark::create(['id' => 39, 'type_id' => 2, 'name' => 'Xerox']);
        Mark::create(['id' => 40, 'type_id' => 2, 'name' => 'Brother']);
        Mark::create(['id' => 41, 'type_id' => 2, 'name' => 'Kyocera']);
        Mark::create(['id' => 42, 'type_id' => 2, 'name' => 'Epson']);
        Mark::create(['id' => 43, 'type_id' => 2, 'name' => 'Ricoh']);
        Mark::create(['id' => 44, 'type_id' => 2, 'name' => 'Konica Minolta']);
        Mark::create(['id' => 45, 'type_id' => 2, 'name' => 'MB']);
        Mark::create(['id' => 46, 'type_id' => 2, 'name' => 'Sharp']);
        Mark::create(['id' => 47, 'type_id' => 2, 'name' => 'Panasonic']);
        Mark::create(['id' => 48, 'type_id' => 2, 'name' => 'Lexmark']);
        Mark::create(['id' => 49, 'type_id' => 3, 'name' => 'DNS']);
        Mark::create(['id' => 50, 'type_id' => 3, 'name' => 'Acer']);
        Mark::create(['id' => 51, 'type_id' => 3, 'name' => 'Asus']);
        Mark::create(['id' => 52, 'type_id' => 3, 'name' => 'Lenovo']);
        Mark::create(['id' => 53, 'type_id' => 3, 'name' => 'Dell']);
        Mark::create(['id' => 54, 'type_id' => 3, 'name' => 'HP']);
        Mark::create(['id' => 55, 'type_id' => 3, 'name' => 'Samsung']);
        Mark::create(['id' => 56, 'type_id' => 3, 'name' => 'Toshiba']);
        Mark::create(['id' => 57, 'type_id' => 3, 'name' => 'Flaptop']);
        Mark::create(['id' => 58, 'type_id' => 3, 'name' => 'GigaBayte']);
        Mark::create(['id' => 59, 'type_id' => 3, 'name' => 'Siemens']);
        Mark::create(['id' => 60, 'type_id' => 3, 'name' => 'CHUWI']);
        Mark::create(['id' => 61, 'type_id' => 3, 'name' => 'AOC']);
        Mark::create(['id' => 62, 'type_id' => 3, 'name' => 'Packard']);
        Mark::create(['id' => 63, 'type_id' => 3, 'name' => 'DEXP']);
        Mark::create(['id' => 64, 'type_id' => 3, 'name' => 'Itel']);
        Mark::create(['id' => 65, 'type_id' => 3, 'name' => 'BENQ']);
        Mark::create(['id' => 66, 'type_id' => 3, 'name' => 'CeLM']);
        Mark::create(['id' => 67, 'type_id' => 4, 'name' => 'Pantum']);
        Mark::create(['id' => 68, 'type_id' => 4, 'name' => 'Samsung']);
        Mark::create(['id' => 69, 'type_id' => 4, 'name' => 'HP']);
        Mark::create(['id' => 70, 'type_id' => 4, 'name' => 'Canon']);
        Mark::create(['id' => 71, 'type_id' => 4, 'name' => 'Xerox']);
        Mark::create(['id' => 72, 'type_id' => 4, 'name' => 'Brother']);
        Mark::create(['id' => 73, 'type_id' => 4, 'name' => 'Kyocera']);
        Mark::create(['id' => 74, 'type_id' => 4, 'name' => 'Epson']);
        Mark::create(['id' => 75, 'type_id' => 4, 'name' => 'Ricon']);
        Mark::create(['id' => 76, 'type_id' => 4, 'name' => 'OKI']);
        Mark::create(['id' => 77, 'type_id' => 4, 'name' => 'Phaser']);
        Mark::create(['id' => 78, 'type_id' => 4, 'name' => 'lexmark']);
        Mark::create(['id' => 79, 'type_id' => 4, 'name' => 'Нет']);
        Mark::create(['id' => 80, 'type_id' => 5, 'name' => 'Depo']);
        Mark::create(['id' => 81, 'type_id' => 5, 'name' => 'ICL']);
        Mark::create(['id' => 82, 'type_id' => 5, 'name' => 'Аквариус']);
        Mark::create(['id' => 83, 'type_id' => 5, 'name' => 'kraftway']);
        Mark::create(['id' => 84, 'type_id' => 5, 'name' => 'Lenovo']);
        Mark::create(['id' => 85, 'type_id' => 5, 'name' => 'R-Style Marshall']);
        Mark::create(['id' => 86, 'type_id' => 5, 'name' => 'RAMEC']);
        Mark::create(['id' => 87, 'type_id' => 5, 'name' => 'HP']);
        Mark::create(['id' => 88, 'type_id' => 5, 'name' => 'SUPERMICRO']);
        Mark::create(['id' => 89, 'type_id' => 5, 'name' => 'Synergy']);
        Mark::create(['id' => 90, 'type_id' => 5, 'name' => 'Andromeda']);
        Mark::create(['id' => 91, 'type_id' => 5, 'name' => 'Iru rock']);
        Mark::create(['id' => 92, 'type_id' => 5, 'name' => 'geg express']);
        Mark::create(['id' => 93, 'type_id' => 5, 'name' => 'Velton']);
        Mark::create(['id' => 94, 'type_id' => 7, 'name' => 'Samsung']);
        Mark::create(['id' => 95, 'type_id' => 7, 'name' => 'DEPO']);
        Mark::create(['id' => 96, 'type_id' => 7, 'name' => 'DNS']);
        Mark::create(['id' => 97, 'type_id' => 7, 'name' => 'Extreme']);
        Mark::create(['id' => 98, 'type_id' => 7, 'name' => 'GigaBayte']);
        Mark::create(['id' => 99, 'type_id' => 7, 'name' => 'Papirrus']);
        Mark::create(['id' => 100, 'type_id' => 7, 'name' => 'R-Style']);
        Mark::create(['id' => 101, 'type_id' => 7, 'name' => 'Proxima']);
        Mark::create(['id' => 102, 'type_id' => 7, 'name' => 'DEXP']);
        Mark::create(['id' => 103, 'type_id' => 7, 'name' => 'CREDO']);
        Mark::create(['id' => 104, 'type_id' => 7, 'name' => 'Pentium']);
        Mark::create(['id' => 105, 'type_id' => 7, 'name' => 'ASUS ']);
        Mark::create(['id' => 106, 'type_id' => 7, 'name' => 'Нет']);
        Mark::create(['id' => 107, 'type_id' => 7, 'name' => 'Lenovo']);
        Mark::create(['id' => 108, 'type_id' => 7, 'name' => 'System manufacturer']);
        Mark::create(['id' => 109, 'type_id' => 7, 'name' => 'MSI']);
        Mark::create(['id' => 110, 'type_id' => 7, 'name' => 'Aquarius']);
        Mark::create(['id' => 111, 'type_id' => 7, 'name' => 'ПЭВМ RAY B102']);
        Mark::create(['id' => 112, 'type_id' => 7, 'name' => 'kraftway']);
        Mark::create(['id' => 113, 'type_id' => 7, 'name' => 'RAMEC']);
        Mark::create(['id' => 114, 'type_id' => 7, 'name' => 'OLDI']);
        Mark::create(['id' => 115, 'type_id' => 7, 'name' => 'НЭТА']);
        Mark::create(['id' => 116, 'type_id' => 7, 'name' => 'VELTON']);
        Mark::create(['id' => 117, 'type_id' => 7, 'name' => 'BRIGHTWINS']);
        Mark::create(['id' => 118, 'type_id' => 7, 'name' => 'LARA']);
        Mark::create(['id' => 119, 'type_id' => 7, 'name' => 'КС']);
        Mark::create(['id' => 120, 'type_id' => 7, 'name' => 'Magellan']);
        Mark::create(['id' => 121, 'type_id' => 7, 'name' => 'intel']);
        Mark::create(['id' => 122, 'type_id' => 7, 'name' => 'AMD']);
        Mark::create(['id' => 123, 'type_id' => 7, 'name' => 'SunPro']);
        Mark::create(['id' => 124, 'type_id' => 7, 'name' => 'InWin']);
        Mark::create(['id' => 125, 'type_id' => 7, 'name' => 'HP']);
        Mark::create(['id' => 126, 'type_id' => 7, 'name' => 'ExeGate']);
        Mark::create(['id' => 127, 'type_id' => 7, 'name' => 'MAGELAN']);
        Mark::create(['id' => 128, 'type_id' => 7, 'name' => 'AeroCool']);
        Mark::create(['id' => 129, 'type_id' => 7, 'name' => 'Krauler']);
        Mark::create(['id' => 130, 'type_id' => 7, 'name' => 'Formoza']);
        Mark::create(['id' => 131, 'type_id' => 7, 'name' => 'Gel E']);
        Mark::create(['id' => 132, 'type_id' => 7, 'name' => 'Colors']);
        Mark::create(['id' => 133, 'type_id' => 7, 'name' => 'AP-1']);
        Mark::create(['id' => 134, 'type_id' => 7, 'name' => 'Power']);
        Mark::create(['id' => 135, 'type_id' => 7, 'name' => 'Super rite master']);
        Mark::create(['id' => 136, 'type_id' => 7, 'name' => 'ZACMAN']);
        Mark::create(['id' => 137, 'type_id' => 7, 'name' => 'BIOSTAR']);
        Mark::create(['id' => 138, 'type_id' => 7, 'name' => 'iRU']);
        Mark::create(['id' => 139, 'type_id' => 7, 'name' => 'Flextron']);
        Mark::create(['id' => 140, 'type_id' => 7, 'name' => 'Acer']);
        Mark::create(['id' => 141, 'type_id' => 7, 'name' => 'Microlab']);
        Mark::create(['id' => 142, 'type_id' => 7, 'name' => 'Micro-Star']);
        Mark::create(['id' => 143, 'type_id' => 7, 'name' => 'Synergy']);
        Mark::create(['id' => 144, 'type_id' => 8, 'name' => 'Samsung']);
        Mark::create(['id' => 145, 'type_id' => 8, 'name' => 'MSI']);
        Mark::create(['id' => 146, 'type_id' => 8, 'name' => 'Asus']);
        Mark::create(['id' => 147, 'type_id' => 8, 'name' => 'Lenovo']);
        Mark::create(['id' => 148, 'type_id' => 8, 'name' => 'Acer']);
        Mark::create(['id' => 149, 'type_id' => 8, 'name' => 'Dell']);
        Mark::create(['id' => 150, 'type_id' => 8, 'name' => 'Philips']);
        Mark::create(['id' => 151, 'type_id' => 8, 'name' => 'Viewsonic']);
        Mark::create(['id' => 152, 'type_id' => 8, 'name' => 'HP']);
        Mark::create(['id' => 153, 'type_id' => 8, 'name' => 'Envision']);
        Mark::create(['id' => 154, 'type_id' => 8, 'name' => 'LG']);
        Mark::create(['id' => 155, 'type_id' => 8, 'name' => 'Huawei']);
        Mark::create(['id' => 156, 'type_id' => 8, 'name' => 'packard bell']);
        Mark::create(['id' => 157, 'type_id' => 8, 'name' => 'iiyama']);
        Mark::create(['id' => 158, 'type_id' => 8, 'name' => 'PROVIEW']);
        Mark::create(['id' => 159, 'type_id' => 8, 'name' => 'Dexp']);
        Mark::create(['id' => 160, 'type_id' => 8, 'name' => 'AOC']);
        Mark::create(['id' => 161, 'type_id' => 8, 'name' => 'NEC']);
        Mark::create(['id' => 162, 'type_id' => 8, 'name' => 'BENQ']);
        Mark::create(['id' => 163, 'type_id' => 8, 'name' => 'Digma']);
        Mark::create(['id' => 164, 'type_id' => 8, 'name' => 'KraftWay']);
        Mark::create(['id' => 165, 'type_id' => 8, 'name' => 'DNS']);
        Mark::create(['id' => 166, 'type_id' => 8, 'name' => 'eMachines']);
        Mark::create(['id' => 167, 'type_id' => 8, 'name' => 'Wintelton']);
        Mark::create(['id' => 168, 'type_id' => 8, 'name' => 'HANNS']);
        Mark::create(['id' => 169, 'type_id' => 8, 'name' => 'MAG']);
        Mark::create(['id' => 170, 'type_id' => 8, 'name' => 'ExeGate']);
        Mark::create(['id' => 171, 'type_id' => 8, 'name' => 'Think Vision']);
        Mark::create(['id' => 172, 'type_id' => 8, 'name' => 'Rombica']);
        Mark::create(['id' => 173, 'type_id' => 8, 'name' => 'Hiper Easy View']);
        Mark::create(['id' => 174, 'type_id' => 8, 'name' => 'Prestigio']);
        Mark::create(['id' => 175, 'type_id' => 8, 'name' => 'LIME']);
        Mark::create(['id' => 176, 'type_id' => 9, 'name' => 'DEPO']);
        Mark::create(['id' => 177, 'type_id' => 9, 'name' => 'IRBIS']);
        Mark::create(['id' => 178, 'type_id' => 9, 'name' => 'Acer']);
        Mark::create(['id' => 179, 'type_id' => 9, 'name' => 'HP']);
        Mark::create(['id' => 180, 'type_id' => 9, 'name' => 'DNS']);
        Mark::create(['id' => 181, 'type_id' => 9, 'name' => 'Asus']);
        Mark::create(['id' => 182, 'type_id' => 9, 'name' => 'MSI']);
        Mark::create(['id' => 183, 'type_id' => 10, 'name' => 'Canon']);
        Mark::create(['id' => 184, 'type_id' => 10, 'name' => 'Kyocera']);
        Mark::create(['id' => 185, 'type_id' => 11, 'name' => 'Realme']);
        Mark::create(['id' => 186, 'type_id' => 11, 'name' => 'Lenovo']);
        Mark::create(['id' => 187, 'type_id' => 11, 'name' => 'DEXP']);
        Mark::create(['id' => 188, 'type_id' => 11, 'name' => 'Huawei']);
        Mark::create(['id' => 189, 'type_id' => 11, 'name' => 'Samsung']);
        Mark::create(['id' => 190, 'type_id' => 11, 'name' => 'OKSI']);
        Mark::create(['id' => 191, 'type_id' => 11, 'name' => 'Apple']);
        Mark::create(['id' => 192, 'type_id' => 11, 'name' => 'Life Tab Plus']);
        Mark::create(['id' => 193, 'type_id' => 5, 'name' => 'Andromeda']);
        Mark::create(['id' => 194, 'type_id' => 5, 'name' => 'Iru rock']);
        Mark::create(['id' => 195, 'type_id' => 5, 'name' => 'geg express']);
        Mark::create(['id' => 196, 'type_id' => 1, 'name' => 'DNS']);
        Mark::create(['id' => 197, 'type_id' => 8, 'name' => 'BENQ']);
        Mark::create(['id' => 198, 'type_id' => 8, 'name' => 'LIME']);
        Mark::create(['id' => 199, 'type_id' => 7, 'name' => 'BIOSTAR']);
        Mark::create(['id' => 200, 'type_id' => 5, 'name' => 'Velton']);
        Mark::create(['id' => 201, 'type_id' => 7, 'name' => 'iRU']);
        Mark::create(['id' => 202, 'type_id' => 7, 'name' => 'Flextron']);
        Mark::create(['id' => 203, 'type_id' => 8, 'name' => 'Acer']);
        Mark::create(['id' => 204, 'type_id' => 7, 'name' => 'Microlab']);
        Mark::create(['id' => 205, 'type_id' => 7, 'name' => 'Micro-Star']);
        Mark::create(['id' => 206, 'type_id' => 9, 'name' => 'Asus']);
        Mark::create(['id' => 207, 'type_id' => 9, 'name' => 'MSI']);
        Mark::create(['id' => 208, 'type_id' => 11, 'name' => 'OKSI']);
        Mark::create(['id' => 209, 'type_id' => 3, 'name' => 'CeLM']);
        Mark::create(['id' => 210, 'type_id' => 11, 'name' => 'Apple']);
        Mark::create(['id' => 211, 'type_id' => 7, 'name' => 'Synergy']);
        Mark::create(['id' => 212, 'type_id' => 1, 'name' => 'BENQ']);
        Mark::create(['id' => 213, 'type_id' => 1, 'name' => 'Samsung']);
        Mark::create(['id' => 214, 'type_id' => 1, 'name' => 'LG']);
        Mark::create(['id' => 215, 'type_id' => 11, 'name' => 'Life Tab Plus']);
    }
}
