<!DOCTYPE html>
<html lang="{{ env('APP_LOCALE') }}">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ env('APP_NAME') }} - @yield('page-name')</title>

    @vite('resources/sass/app.sass')
    @vite('resources/js/app.js')

    @yield('include-vite')
</head>

<body>
    @include('include.header')
    <div class="page-content mini-scroll">
        @include('include.navigation')
        <div class="big-block">
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore a magnam maxime ratione numquam! Necessitatibus laborum quis eligendi totam eaque ut facilis, in animi eveniet porro quas vitae culpa! Doloremque?
            Ratione doloremque, necessitatibus quisquam ducimus eius dolores assumenda a deleniti modi eos aut fugit inventore dolor culpa, cupiditate, suscipit aspernatur incidunt magni libero! Ab porro earum nisi aliquam assumenda mollitia!
            Modi doloremque quas illum beatae suscipit quis ratione vel. Aperiam libero enim mollitia esse, aliquam illo numquam, quod deserunt reprehenderit dolores pariatur hic saepe et. Fugit libero unde reprehenderit facere.
            Itaque minus quos cum velit hic facilis ducimus, expedita omnis, asperiores illo est illum. Voluptatibus sed voluptatem nemo, odio illo, laboriosam a quaerat necessitatibus asperiores dolores, doloremque consectetur amet. Id.
            Aut officia reiciendis autem est quod inventore corporis error illo voluptates magni accusantium placeat tempore debitis voluptatem earum facere laudantium quisquam, repellendus, similique nemo nobis explicabo quae fugiat eaque. Dolore.
            Amet eaque voluptatum dolorum, voluptates suscipit sit molestias impedit dolore! Harum, minus tenetur iusto consequuntur quo qui cumque fugiat ipsam, perferendis ut velit! Fuga cumque accusamus impedit deserunt facilis doloremque!
            Quibusdam eum quae similique velit quidem quo sit. Omnis temporibus, repellat corrupti odit, quidem nostrum aspernatur, facere quisquam vero dolorum aperiam consequuntur enim dolor quod sequi velit magnam repudiandae alias!
            Et sint reiciendis ullam, dignissimos repellat aliquid natus tempora aut optio labore iusto minima! Consequatur, beatae quis. Quidem rerum laudantium molestiae ea quo repellat fugiat, vel beatae officia sapiente exercitationem.
            Sunt ex rem provident distinctio mollitia vitae, porro repellendus odio aliquid ea minima dolores, suscipit officia nulla. Expedita, eveniet possimus error quibusdam, repudiandae incidunt consectetur voluptatem libero iste sed dicta!
            Maiores nulla laudantium enim omnis sit maxime, nemo ullam, non, distinctio iste praesentium libero nisi? Non facilis rerum molestias corporis. Maxime, aliquid! Omnis ea qui deserunt doloribus. Assumenda, est hic!
            Quaerat similique accusantium incidunt harum culpa illo, a, rem veritatis voluptas molestias voluptates, dolores consequuntur distinctio perspiciatis accusamus doloremque inventore. Quod laudantium sapiente reiciendis sunt quidem perspiciatis nemo consequatur itaque.
            Rem laboriosam voluptatum nam quas qui, corrupti esse veritatis repellat rerum atque magni optio perferendis est, impedit pariatur enim. Blanditiis, minima. Nesciunt numquam autem pariatur fugit sit voluptas laborum optio.
            Dolor totam obcaecati dolore rerum, vitae adipisci aliquam asperiores officiis quo illum nostrum. Reprehenderit quia veniam provident dolorem ducimus odio atque? Necessitatibus esse nisi, repellendus sit dicta sequi perferendis doloremque.
            Placeat mollitia incidunt pariatur harum repellat at quod doloribus ratione tempore aliquam voluptatum minima possimus, sint sed quae expedita quia soluta nemo facilis laborum cumque tempora asperiores! Fugiat, fuga aut?
            Ducimus facere sed eos pariatur saepe laborum quam enim, itaque maiores dolorem exercitationem iure necessitatibus voluptatem odio nesciunt incidunt excepturi eum. Eius quidem officiis nobis laudantium fugit aspernatur sapiente distinctio.
            Molestiae atque, exercitationem perspiciatis esse asperiores optio, quod fugiat labore expedita hic ducimus laborum non aliquam harum libero nam quasi dignissimos dicta! Saepe, tempora! Consequuntur tempora laborum sapiente fuga est.
            Laborum laudantium eos officiis, sint eaque aliquam fugiat minima itaque! Illum laudantium adipisci beatae sit. Officia quisquam iste eligendi aliquam sit, nisi aut perferendis reprehenderit! Sed at rem corrupti sit?
            Iste aut perspiciatis molestiae totam aperiam veritatis consequuntur facere ad, quisquam praesentium sed quibusdam tempore quidem, fuga dolorum expedita laboriosam, reiciendis at. Sequi reprehenderit aut dolore dolorum sapiente totam? Veniam.
            Nam magni commodi ea, iste nostrum modi sunt aliquid porro atque praesentium soluta doloremque qui sapiente consectetur nulla vitae. Recusandae odio omnis doloremque exercitationem voluptas impedit hic nihil enim libero.
            Tempora aliquam laudantium, adipisci aut sunt repudiandae quo, tempore illo unde dicta quasi minus nesciunt quaerat ex, pariatur est? Delectus cum rem aperiam pariatur error placeat impedit repudiandae expedita incidunt?
            Aliquam distinctio animi fuga quaerat error, sit quibusdam voluptates explicabo aut delectus dignissimos libero rem quod dolorem dolore possimus dicta assumenda illum fugiat, ratione voluptatibus! Ex beatae in ratione esse.
            Dignissimos deserunt ipsa necessitatibus! Recusandae error eos totam quos laboriosam, tempora quas assumenda veniam delectus dignissimos, omnis veritatis quaerat pariatur tempore doloribus asperiores expedita sapiente dolores aperiam voluptate repudiandae officia!
            Iure, qui nulla voluptates alias expedita, temporibus porro soluta maxime dolorem excepturi atque pariatur aut id cum odio provident itaque sunt natus? Eaque mollitia omnis perferendis autem voluptas repellendus itaque?
            Animi deleniti nobis libero veniam explicabo neque magni veritatis nulla iste eveniet eos labore cum, maxime soluta cupiditate atque exercitationem laudantium debitis corporis inventore quisquam asperiores repellendus maiores. Possimus, omnis.
            Error dolores accusantium maiores. Et iusto consectetur corporis suscipit molestiae cum nisi, non minima quibusdam beatae nihil eum ratione sit eos sapiente hic perferendis veniam exercitationem? Doloremque soluta enim omnis.
            Est unde rem obcaecati, officiis maiores itaque! Dolorum sit placeat aut ipsam necessitatibus ea aperiam officiis id magni eius, nam nesciunt maxime suscipit labore iste dolor, commodi, vel sed tempora.
            Earum praesentium ab inventore ipsa voluptates esse autem fuga consequatur vitae odit, eligendi eaque unde sapiente nam quas, necessitatibus ipsum molestiae? Numquam, incidunt quas. Sed quibusdam beatae omnis aliquam corporis!
            Tenetur, nesciunt? Ipsa possimus alias, vitae saepe laborum, doloribus molestiae enim veritatis dolorem pariatur blanditiis earum recusandae vero dolores necessitatibus quod neque odio adipisci omnis quas cupiditate nihil! Porro, quisquam?
            Quas quos, velit harum praesentium repellat nam neque laborum explicabo, in quod sit quo, ex dolor esse temporibus possimus aliquam expedita suscipit similique voluptatum facilis iste omnis? Doloremque, nobis ex?
            Id esse ullam enim vel hic commodi velit nulla corporis recusandae atque ipsa accusamus delectus repudiandae quis est aliquam, natus nam quae ipsam dicta error eos repellat. Sequi, sint architecto?
            Dolores, non numquam! Eveniet vel quam, dolor nostrum veritatis consectetur fugiat perferendis, quos nesciunt sint eos molestiae! Totam, ea corrupti. Et magnam consequatur quo non, cum dignissimos ut exercitationem ea!
            Reprehenderit voluptatum odit eos consequatur sed, id voluptate, doloribus tempora facilis nisi explicabo, alias hic quod quibusdam. Deserunt voluptate nesciunt reprehenderit, quasi architecto voluptas molestiae ab odit, quas ipsa maiores.
            Magnam totam, reprehenderit doloribus consequatur accusamus commodi harum, optio exercitationem possimus, pariatur a voluptatibus minus quas quos nulla veritatis sequi vero deleniti consequuntur. Ipsa in at doloribus natus, blanditiis cum.
            Saepe ipsum assumenda voluptatem quisquam beatae porro! Expedita quia praesentium optio error blanditiis porro aspernatur repudiandae deserunt reprehenderit veniam a, ipsum explicabo necessitatibus tempore provident repellat ducimus enim nostrum eligendi!
            Sequi debitis, corporis voluptas alias velit unde, magnam maxime expedita veritatis dolore vero quo voluptatum numquam libero, doloremque totam distinctio asperiores dolores optio labore? Architecto, unde. Nihil dolor doloribus eveniet?
            Neque tempora voluptatem molestiae voluptate necessitatibus ratione autem ut libero corrupti odit ea odio harum animi illum, vero dicta? Sed iste magni maiores velit rerum unde ullam sapiente quasi nihil!
            Qui veniam hic odio labore deleniti illum, placeat nam? Animi velit eius excepturi tempora corporis, inventore quo. Tenetur sed incidunt quod in. Consectetur, modi aspernatur eius illo obcaecati sed nobis?
            Labore animi aperiam nemo aliquam aliquid vitae optio sit vero fuga quibusdam tenetur distinctio laborum odio accusamus, maxime perferendis autem ullam asperiores id nisi. Incidunt laborum fugit labore magni quaerat!
            Consequuntur in, sunt ducimus eum autem vero asperiores hic ullam debitis nulla? Animi atque, maiores esse eligendi a natus impedit corporis itaque? Magni perspiciatis repudiandae libero rerum assumenda, excepturi officiis!
            Quis nesciunt rem soluta corrupti sint velit architecto dolor porro, ab dolore harum, pariatur iure qui autem odit hic nihil quidem reiciendis unde natus quae optio vitae quibusdam accusantium. Vero.
            Nemo libero harum minus ipsa pariatur voluptates explicabo ex, velit quaerat rerum quo quisquam officiis quam dolor earum optio eaque molestiae est eius voluptas? Suscipit corrupti aut id dignissimos perferendis!
            Vitae quae ducimus placeat! Dolore praesentium quo labore at id alias, nostrum ad voluptatibus ipsum esse neque minima dignissimos quos, fuga tempore rem delectus sequi doloribus quae numquam quis ipsa.
            Voluptas, laborum facilis voluptate repellat tenetur earum optio mollitia necessitatibus laboriosam, sequi sed aliquid esse, doloribus soluta ducimus dicta libero iure quae deserunt magni veritatis. Magnam amet earum incidunt laboriosam?
            A debitis corporis perferendis eligendi vel provident illum voluptatum deserunt dolorum libero asperiores, minus error qui pariatur assumenda ducimus ipsa quod nulla doloremque dolor animi neque repudiandae odio. Ducimus, exercitationem.
            Odio molestiae omnis obcaecati! Doloribus architecto cupiditate non consequatur incidunt iste temporibus perspiciatis numquam ad, ullam, molestiae nostrum aperiam. Exercitationem voluptates architecto vero quos odit esse, minima repellat fugit rem.
            Dolorum dignissimos corporis magni, harum vel laborum quidem deserunt officiis temporibus consequuntur ullam? Rerum, autem doloribus inventore aut omnis laboriosam vero nesciunt earum eos quam repudiandae facere repellat fugit aliquid?
            Alias voluptates laudantium recusandae officia dolor ipsa aliquid doloribus quaerat eligendi corrupti aspernatur id quibusdam velit nulla temporibus, beatae quasi sit ducimus nemo, vero, veniam magnam minima earum commodi! Iure.
            Voluptatibus illum fuga dolores deleniti corrupti asperiores praesentium molestiae reprehenderit autem error optio dignissimos accusantium repellat aut, magni, cumque culpa recusandae minus fugiat nemo aspernatur aperiam quis, ratione quas? Pariatur.
            Optio in expedita reiciendis temporibus dolorem similique impedit tempora id asperiores possimus magnam itaque aliquid officiis maxime adipisci deserunt ullam provident odit, suscipit sed ipsum debitis voluptas! Quibusdam, aspernatur fuga.
            Deleniti, quidem perferendis ut delectus aperiam praesentium saepe neque minima ex rem quas illum sequi. Aspernatur laborum nostrum laudantium pariatur voluptatem repudiandae ad, non asperiores, vel quod aperiam natus. Impedit.
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Debitis dignissimos laborum earum amet voluptatum, dolorem magnam minima mollitia dolorum obcaecati necessitatibus est voluptates non culpa nulla voluptas perferendis, officiis deleniti.
            Impedit ducimus adipisci quidem totam dolorem exercitationem magni nesciunt, ipsam facilis sit ratione ipsa, aspernatur tempore. Accusantium, corrupti. Eius, nobis nihil deserunt animi qui aperiam exercitationem dicta aut maxime ab.
            Cumque molestiae similique ratione iste aperiam dolorum laborum corporis cupiditate veritatis sapiente, deserunt nemo iure, quis ad et aliquid necessitatibus alias deleniti totam possimus magnam voluptate facere? Ad, dolorem nostrum.
            Deleniti sit molestiae sunt natus alias dolorum consequatur, deserunt modi voluptatum odit, ducimus id exercitationem, doloremque laborum fuga voluptatibus quod officiis blanditiis? Ullam ad, libero voluptatum hic fugit inventore illo!
            Necessitatibus hic minima animi nostrum facere eveniet optio illum, voluptatem voluptatibus enim blanditiis labore fuga possimus? Odio optio animi ad harum eius porro voluptatem molestias assumenda! Magnam animi distinctio suscipit!
            Libero, nam dolore! Sunt nisi deleniti dicta, tempore voluptate doloribus magni voluptas repellat amet qui! Accusamus necessitatibus excepturi illum esse deleniti nobis voluptas cupiditate expedita. Sequi natus harum odio atque?
            Tempora necessitatibus iste, iusto asperiores soluta veniam beatae est quis odit deserunt ipsum libero sit atque nam voluptates velit minus? Quidem commodi totam voluptas molestiae et minima, nobis suscipit debitis.
            At incidunt, neque maxime dolore, rerum qui blanditiis quam quas delectus, earum porro iste! Excepturi, ipsa aliquid voluptate eaque labore eligendi tempore nesciunt, perspiciatis aperiam deleniti ex, repellat incidunt facere!
            Id, ducimus quam non praesentium ad, qui natus, repellat soluta eos explicabo adipisci distinctio fugit quia ipsa error. Blanditiis nulla consequatur eum dolorum, numquam voluptatem reprehenderit magnam quo facere similique!
            Provident, veritatis. Provident, ad ipsam iusto sit placeat exercitationem nobis voluptatem consectetur id quidem dolore deserunt aliquid neque, quisquam suscipit corrupti quibusdam veritatis mollitia consequatur, non voluptates? Nisi, quidem nulla?
            Quisquam minus illo animi commodi, officia nisi iste incidunt aliquam tenetur, saepe et excepturi deserunt voluptatibus? Magni molestias necessitatibus ex libero nemo odio, repellat, eius, perspiciatis eveniet sapiente atque doloribus!
            Quasi eveniet eaque tenetur, soluta iste fugit labore inventore! Dolorem odit enim ullam adipisci explicabo assumenda, architecto a et debitis porro saepe minima modi ipsam cumque eius similique! Autem, repellendus!
            Accusantium facilis quibusdam excepturi quia fugiat dolore blanditiis vero tenetur nulla beatae sint, voluptatem ullam id adipisci debitis! Dolor ad facere molestiae consectetur aliquam quis doloribus atque et, magnam nisi.
            Porro perspiciatis aut voluptate ipsa recusandae, ab aspernatur et a ipsam cum reiciendis quasi dicta temporibus delectus veritatis quia quas blanditiis similique aliquam labore consectetur numquam harum quisquam. Quia, voluptatibus?
            Natus ab soluta ratione minima. Labore sed mollitia consectetur quo autem deleniti facere molestias illo voluptate, repellat saepe qui culpa natus ab quam nulla nemo expedita velit possimus voluptatibus. Est?
            Nam optio asperiores quidem, obcaecati illum incidunt facilis consequatur, eligendi enim omnis tenetur? Excepturi qui odit quia, aut ea, voluptates laboriosam maxime, veritatis temporibus non repudiandae voluptatibus praesentium libero maiores?
            Quibusdam, sint pariatur. Quisquam quam eaque autem sit iste nisi inventore nostrum, perspiciatis vitae rerum a, nulla explicabo repellat in reiciendis voluptatibus necessitatibus quas laudantium corporis deleniti reprehenderit ad eius!
            Eum cupiditate placeat doloremque doloribus voluptates amet, modi aperiam temporibus nisi cum. Eum inventore unde, tenetur quos labore corrupti autem fugit nostrum. Sapiente facere ullam impedit vero at natus fugiat.
            Dolorem assumenda officiis corporis quibusdam libero in, minus qui laudantium nemo explicabo illo, doloremque expedita quod odio labore! Autem facilis ipsa earum inventore impedit amet molestias ea in possimus! Veniam.
            Voluptatum, voluptas minus. In accusantium dolore nisi? Enim assumenda qui perferendis quibusdam repellendus nostrum quia cumque quas recusandae ea nihil quisquam corrupti amet, quam omnis accusantium vitae reprehenderit vero optio.
            Placeat sequi explicabo nisi, quas nulla praesentium, dignissimos impedit illum, doloribus ex assumenda. Debitis accusantium voluptas cupiditate deserunt incidunt a quidem quasi, blanditiis nobis cum, quos nemo inventore eligendi perspiciatis.
            Eaque, ducimus non excepturi hic omnis cumque molestias ut soluta optio eum asperiores officiis eius quae error quia ipsam magnam facilis sequi! Nesciunt iusto architecto similique enim nam nihil! Corrupti.
            Ducimus, quibusdam ipsum! Nulla perspiciatis, illo temporibus ipsum minima suscipit est dicta inventore sint obcaecati, asperiores a neque ullam eligendi. Dignissimos, reiciendis accusantium eveniet dolores illum quasi vero dolorem minima?
            Molestiae aliquam omnis vero nisi dicta. Culpa iste eligendi saepe qui! Et cupiditate consequuntur laboriosam rem numquam quisquam eligendi. Amet ad tempora veritatis recusandae hic ratione corporis enim quidem iusto.
            Ratione quia deleniti perspiciatis quisquam quibusdam velit minima facilis amet dolorem, vitae officiis tempora laboriosam necessitatibus. Pariatur, alias amet modi labore dolorum quis harum cupiditate voluptatum laboriosam ullam consequuntur eaque?
            Facere ex nobis recusandae non. Ad, magnam autem quos illo delectus tempore repudiandae asperiores cumque itaque quis dicta enim tenetur voluptatum assumenda explicabo excepturi! Officiis non illum aspernatur. Consequuntur, porro.
            Nemo nesciunt autem beatae explicabo dolore ex sapiente provident, officiis ipsum. Quibusdam excepturi iusto deleniti maiores eligendi numquam maxime? Eveniet corporis quas vero voluptas fugiat doloribus nulla dolorum atque sequi.
            Id corrupti facere laboriosam quidem maiores cum quam perspiciatis earum, ea vitae dolorum iusto unde debitis, quibusdam sed maxime est necessitatibus, impedit harum. Alias sapiente nemo minus commodi blanditiis iste.
            Vitae debitis ducimus asperiores totam commodi iure nulla veritatis fuga? Quibusdam alias natus iusto possimus, ullam, quisquam iure dolor hic, est sunt unde! Odit porro quidem, omnis accusantium maxime et.
            Amet sint delectus omnis ratione optio tempore nesciunt repellat, nihil aliquam aliquid soluta quis error officiis exercitationem vitae consectetur ipsa cum, accusamus quia cumque odio? Animi quidem earum adipisci? Assumenda.
            Aspernatur doloribus error sed distinctio perspiciatis laborum placeat quia porro repellendus id soluta cum similique nulla minima quisquam nemo, eius possimus nobis animi quaerat! Velit deleniti eum animi quasi optio?
            Aut reiciendis alias accusamus accusantium qui quos, id vero repellat cupiditate, dolor provident sed. Molestias, veniam! Dolore rerum quibusdam molestias totam corporis sit reprehenderit et neque voluptate ab, numquam recusandae?
            Debitis ex reiciendis possimus ea odio provident vero sed aliquid aut? Quibusdam saepe eum dolorum. Dolor maxime quo mollitia, ea saepe quod debitis, iusto modi illum, repudiandae vero tenetur alias.
            Aliquam aliquid reiciendis exercitationem architecto? Illum quisquam asperiores voluptatem repudiandae. Eaque exercitationem incidunt quisquam. Rerum nostrum impedit fugiat quas, cum possimus ipsum fugit ut ad molestiae in dicta, nihil alias.
            Deleniti assumenda aperiam quibusdam ipsa itaque fugiat sunt perferendis iusto perspiciatis! Consectetur nulla voluptatum minima placeat sit, commodi accusantium, dolorum in, exercitationem eos nostrum distinctio qui deleniti provident eum ducimus.
            Vel assumenda non voluptatem excepturi sunt repudiandae pariatur molestias facilis ullam asperiores ducimus atque unde reprehenderit distinctio architecto magni, culpa enim doloribus, error fugiat quo suscipit! Eligendi quibusdam assumenda perferendis.
            Accusamus, incidunt? Dolores, assumenda consequuntur quidem quis minima et magni tempora aliquam dolor sunt doloribus nisi quaerat ipsum delectus. Veniam maxime porro nemo quibusdam odio possimus, excepturi distinctio quo autem.
            Quam quidem laboriosam, saepe natus corporis earum itaque nulla exercitationem iusto? Commodi doloribus perferendis repellendus maxime neque, enim maiores suscipit labore, ea atque, eum itaque corrupti deleniti incidunt tempora beatae!
            Rem aspernatur nesciunt voluptates? Blanditiis quidem voluptatum officiis libero, eligendi laborum! Blanditiis nulla quasi accusantium exercitationem error! Harum itaque nam beatae laudantium quod non, eos facere dolorum consectetur tempore fugit.
            Corporis numquam sunt provident labore ut tenetur, ea at sed laudantium delectus quis harum placeat unde vel quas repellendus excepturi velit? Fugit, sapiente obcaecati eveniet facilis amet expedita similique non?
            Iure nemo adipisci incidunt iste enim. Nulla natus atque neque? Architecto a, exercitationem minima praesentium officiis temporibus tempora tenetur est autem, voluptate fugiat nihil facilis id excepturi accusantium, repellat aperiam.
            Laborum, doloremque. Rem qui error repellat perferendis pariatur hic necessitatibus ex similique nihil rerum. Perspiciatis deleniti earum labore neque, aliquid corrupti necessitatibus repellat illo corporis voluptatum distinctio incidunt dolorum iusto.
            Ex illum, explicabo repudiandae ducimus voluptate autem veritatis. Ab libero necessitatibus iure voluptates rem incidunt impedit amet, at temporibus omnis ducimus praesentium similique voluptatem mollitia saepe tenetur, itaque in atque!
            Perspiciatis distinctio sint veritatis, dolore aliquid dolorum deserunt cupiditate quos officiis? Qui itaque dicta accusantium maiores vero rem temporibus magnam. Minima ullam earum qui fugit iste perspiciatis sit quae provident!
            Debitis distinctio aspernatur vero, et temporibus quidem. Facilis rem distinctio fuga ab vero id voluptatibus repellendus necessitatibus? Atque debitis eveniet quaerat repellat nesciunt temporibus doloremque sint cum veritatis. Ab, odio.
            Architecto eos exercitationem quaerat libero natus unde tempore voluptatum reiciendis placeat repellat adipisci quo nesciunt assumenda, quos inventore, perferendis incidunt possimus tempora. Doloremque, quis iusto accusamus asperiores rem magnam vero.
            Sint officia eos repudiandae consequatur, velit temporibus alias minus illum voluptas libero ipsa quibusdam modi voluptatem odio iste esse qui aliquam magnam in, ullam quo repellat, nam expedita. Harum, nihil.
            Illum sunt ullam id delectus! Voluptatem incidunt laborum dolores. Dolorem deleniti rerum dolor, sapiente perferendis voluptatem maxime odit quae voluptatibus dolores ratione harum, tenetur ex, modi est numquam velit fugit?
            Magni, vitae minima modi odio ipsa et cumque expedita itaque corrupti voluptate! Iure dolore sed assumenda facilis eligendi culpa quis nulla molestias deleniti et! Inventore debitis vel iure pariatur optio.
            Quas, molestias? Possimus quaerat aliquid dicta sit optio a nisi illum ratione dignissimos! Blanditiis nostrum consequatur doloribus assumenda officia ipsum libero ducimus at possimus, totam aut pariatur impedit modi qui?
            Numquam voluptatem voluptas impedit praesentium. Quo, temporibus illum modi fugiat ipsam quibusdam, numquam facilis sit voluptas expedita quasi nam error illo blanditiis! Obcaecati reiciendis rerum iusto. Aspernatur culpa exercitationem eligendi.
            Ab labore et quibusdam? Modi rem dolores maiores voluptatem, adipisci, earum at quo unde dolorum sint nihil, animi ratione inventore culpa eligendi illum voluptatibus eaque blanditiis ipsa optio architecto. Hic.
            Voluptate consectetur nesciunt alias. Repudiandae id blanditiis quam laudantium optio quasi dicta, laborum illum velit exercitationem atque, doloribus maxime voluptate? Cumque in voluptatibus pariatur, fugiat architecto quidem reprehenderit dignissimos non.
            Veniam nesciunt ut inventore praesentium corporis eveniet possimus dolore accusantium impedit beatae nisi molestias quasi architecto quia, quisquam nemo assumenda numquam officiis nobis excepturi fugiat itaque? Veritatis laudantium quis modi!
            Quibusdam perferendis, eligendi dicta molestiae cupiditate illum quaerat pariatur ea officiis minus. Consequuntur quibusdam est, voluptate laboriosam, ab libero accusamus nam amet sed debitis ullam reiciendis, vel eum iusto. Ad!
            Saepe in iste odit sed iure expedita? Fugiat accusantium nostrum libero aut, eaque reprehenderit exercitationem laudantium minima magnam nulla officia, reiciendis ullam. Neque dolores similique qui incidunt, rem aperiam doloremque.
            Molestiae, atque excepturi, delectus incidunt ullam fugiat, odit nam error expedita aperiam quaerat dolorum non commodi porro inventore impedit corporis dolor! Nostrum at cum earum libero ex fuga deleniti consectetur?
            Reprehenderit deserunt velit deleniti facere consequatur cum nesciunt eum non praesentium doloribus quia, sint libero temporibus et repellendus sit eaque eveniet sapiente! A architecto laboriosam error ut excepturi totam eaque!
            Commodi neque molestiae sapiente blanditiis asperiores culpa optio. Magni corporis voluptates reiciendis nemo iure at officia nesciunt velit. Voluptate rerum consequuntur repellat quam porro nam suscipit id impedit magni nobis!
            Tempore commodi voluptate deserunt repellat eligendi dignissimos odit, impedit, beatae nobis ipsum aliquam laudantium quibusdam harum incidunt hic laboriosam nemo fugit corrupti nostrum est minus. A vero voluptatum velit fugiat!
            Sed eaque, animi architecto laborum modi iste deserunt est vel rem error excepturi quae, ipsam id ipsum culpa sint cupiditate, tempora veritatis non? Magni, deleniti aliquam at sequi quae blanditiis!
            Aspernatur voluptatem amet saepe aperiam! Provident quod nesciunt perferendis ullam aut unde cumque animi, officiis dolore dolorum, corrupti totam illo. Quisquam earum cum quas minus alias? Ab exercitationem sequi hic?
            Blanditiis quae numquam, et ad asperiores perspiciatis nobis fuga praesentium dolorum a at neque aliquam quam eveniet officiis, adipisci explicabo vitae quis. Voluptatum totam aperiam veniam ab eaque. Laborum, laboriosam.
            Temporibus excepturi obcaecati blanditiis, quam exercitationem cum sed labore hic reiciendis iusto laboriosam, odit similique sequi dolor ad eveniet dolorem consequuntur suscipit, sint ab itaque ipsam. Minus tempora recusandae mollitia!
            Ab optio deleniti sed dolorum nemo dolores accusantium corrupti consequuntur facere sapiente rem, enim mollitia neque fugit ipsum, non illo assumenda est eos, pariatur id molestiae reiciendis? Odio, consequatur rerum.
            A assumenda doloribus autem, quas eligendi amet rerum tenetur debitis facilis sit excepturi! Iste suscipit dolore, voluptate hic inventore iusto amet earum voluptatem minus, iure quisquam facere odio incidunt. Magnam.
            Sapiente tempora laborum mollitia corrupti earum fugiat eum, repellat cum unde est dolor quo asperiores ullam? Esse, eveniet. Tempore libero ipsa voluptatem commodi, dolorum perspiciatis voluptatum odit voluptatibus fugit eos?
            Nisi, consequuntur? Eaque expedita deserunt veritatis fuga reiciendis. Voluptatem fugiat nobis nisi autem quo nulla, deserunt, alias itaque necessitatibus sint reprehenderit labore perspiciatis similique voluptatum iure error, voluptates delectus ipsam.
            Explicabo, enim quae? Assumenda earum soluta neque perferendis, minima vitae illo esse consequatur iusto quo quasi dolorem ex nesciunt recusandae reprehenderit ducimus, voluptatum magnam obcaecati veritatis quod incidunt perspiciatis explicabo.
            Distinctio quaerat debitis facere. Libero repellat sapiente maiores quibusdam recusandae harum officiis iusto eum incidunt. Voluptatum numquam ex ducimus sequi nostrum tempore culpa, totam dolor, explicabo et fugit delectus est.
            Ab commodi quos pariatur ullam nobis esse optio? Quas soluta voluptas, magni dolore velit nam ducimus inventore provident sed, perferendis repudiandae porro id cumque error minima accusantium tempora labore qui.
            Et minus eos voluptas illo temporibus voluptatibus sequi sit veritatis voluptates tempora dolorem distinctio impedit hic corrupti at ab neque, corporis eligendi unde architecto officia possimus sed nostrum? Dicta, saepe.
            Nesciunt similique recusandae optio explicabo labore quos cumque sequi fugiat unde. Repellendus illum sequi, recusandae possimus sed similique, delectus maxime laborum neque, necessitatibus vitae voluptate dolores consequuntur deleniti non ratione!
            Minima iste dolorem a magni laborum maiores optio odio reprehenderit amet aspernatur aut facilis corrupti ut delectus rem eos, assumenda cumque ab cupiditate dolore. Itaque quae inventore repellat magni hic.
            Ducimus sapiente aliquam quae accusantium dolorum quis nisi voluptatum expedita, nesciunt praesentium facere adipisci perferendis quod aliquid dolores aut? In ratione rerum ab nulla iste mollitia beatae possimus perferendis sit.
            Fugiat illo aliquid consequatur ullam perspiciatis! Veritatis ad, perferendis vero eos voluptas laborum enim odit reiciendis quidem dolores unde velit libero eum cumque ea recusandae possimus in. Similique, blanditiis eius.
            Eveniet magnam accusamus iure, debitis repudiandae laudantium corrupti. Non, assumenda odio praesentium vel quidem error mollitia! Eum eaque ad quod obcaecati, magni nihil, repellat, odit blanditiis at placeat laboriosam excepturi.
            Modi debitis quidem voluptate expedita vel excepturi architecto nostrum alias? Beatae, incidunt ad nesciunt vero sapiente culpa iste eaque cum cumque accusantium autem, voluptatibus molestias ipsa perspiciatis qui deleniti minus?
            Voluptatibus veritatis molestias aperiam, eos id hic qui, inventore a nihil fugiat magni totam reiciendis facere culpa numquam. Fuga modi veniam corrupti nemo eligendi iure ipsa unde quia quisquam mollitia?
            Vel minima officia adipisci fugiat, quisquam ab, earum sit doloribus minus similique necessitatibus, repudiandae nemo natus deleniti unde saepe veritatis eveniet voluptatum aliquam? Nulla cumque repudiandae at, illum unde facere?
            A tenetur magni illum itaque delectus ipsa, nulla voluptas consequatur commodi nostrum molestiae, ut aperiam impedit ipsam, suscipit praesentium non earum. Soluta doloribus, dolores a fugit quae temporibus perspiciatis in.
            Reiciendis dolore, quasi delectus dolorem, ex molestiae explicabo exercitationem suscipit repudiandae aliquid, facilis animi sunt rerum saepe nulla soluta quo nobis possimus nisi. Voluptates eius minus iste voluptatem earum laborum.
            Obcaecati, deserunt necessitatibus? Sed veritatis quasi, laboriosam asperiores vitae nihil distinctio reprehenderit illo natus mollitia aliquam minima quae obcaecati, deserunt optio perferendis deleniti accusamus impedit quibusdam quia quisquam similique? Architecto!
            Repudiandae voluptates dicta veritatis numquam, facere voluptatum. Consectetur recusandae adipisci vitae harum qui incidunt pariatur deserunt laboriosam, quaerat voluptate. Eius dolores est dolore nulla aut quo consequuntur sequi doloribus quos!
            Nesciunt non nobis minima debitis excepturi, alias quas atque ut perspiciatis doloremque vero porro est aliquid impedit. Eum mollitia maiores, quidem sapiente fuga natus. Sed, quos! Neque exercitationem quia voluptates!
            Harum, temporibus necessitatibus dolorem culpa rerum corporis nulla, in dolorum nisi ullam quo, fugit aut sequi. Unde, voluptatem nostrum fugit dolore perferendis nesciunt harum, amet fuga libero voluptatibus repellendus illum!
            Optio in quis accusantium magnam sapiente aperiam voluptas, corrupti, itaque explicabo consequuntur nemo doloremque molestiae minus fugit ut voluptates. Possimus sed ut tempora amet asperiores sunt saepe! Totam, reiciendis aspernatur.
            Vitae, modi. Illum veritatis, vero quod quibusdam reprehenderit, iusto dolor laboriosam voluptatibus eveniet quidem odit atque aliquam! Dolorum, odio! Id culpa beatae dignissimos expedita sapiente! Fugit quam architecto ab perspiciatis!
            Unde repellat nulla iure numquam sunt laboriosam rerum voluptatibus, adipisci fugit eum ad cumque magnam omnis, saepe aut blanditiis. Velit perspiciatis dolorem dicta iste deleniti maiores enim beatae labore nulla?
            Nostrum sed quod maiores id dolore, eaque et aliquam aut exercitationem quidem nisi beatae aliquid, ipsum ad mollitia animi fugiat deleniti veritatis, tenetur dignissimos nam nulla hic porro optio. Earum?
            Sunt esse eligendi distinctio culpa quas quo inventore autem, ea, minima voluptate voluptates? Tempore asperiores dolore ipsum architecto, nisi laborum doloribus recusandae illum eum! Id eveniet impedit asperiores libero ducimus?
            Libero dicta consequuntur veniam fuga nemo ipsam, ipsum, earum distinctio iure, rem voluptas. Quaerat esse suscipit nesciunt. Ab laudantium corrupti cupiditate, maiores tenetur quia nisi odit optio cum alias repellendus.
            Rerum distinctio a temporibus. Quam, incidunt, excepturi porro molestias accusantium velit officiis obcaecati voluptatibus dolor officia ex vero error? Consequatur voluptatibus alias ipsa iure a sunt et eum qui aut.
            Autem, voluptas debitis blanditiis facere vero exercitationem! Quis voluptates, cupiditate accusamus dolorem quia quibusdam quam. Corrupti accusantium amet, corporis rem error quasi vitae. Sed aliquam beatae eligendi aperiam nemo vitae.
            Nemo iure, hic illum illo aliquam iste repellat assumenda ea natus quis dignissimos commodi sapiente soluta. Sapiente, eum ut laboriosam, ex obcaecati enim repellendus vitae laborum, fuga id rerum nemo!
            Enim, odio? Consectetur ratione asperiores cupiditate rerum reiciendis aliquid neque maxime in atque repellendus error consequuntur eum ea dignissimos odit placeat eligendi qui labore quasi architecto quod delectus, explicabo tenetur!
            Quod perspiciatis ex obcaecati, earum excepturi libero iusto explicabo. Pariatur, labore? Provident praesentium, totam mollitia reprehenderit illum aliquid voluptas nesciunt voluptatum eos, inventore nemo commodi culpa exercitationem atque aut? Rem.
            Dolorem esse neque commodi repudiandae quis iure cum distinctio, animi soluta, dolor dolorum et aperiam explicabo ipsam sint quibusdam a sed doloribus. Inventore facilis repellendus repudiandae non maxime minima veniam?
            Nihil ipsum eligendi voluptates ab, minus cum delectus recusandae id unde dolor consectetur corporis porro veritatis incidunt officiis reiciendis aut officia facilis! Adipisci ut totam a aperiam ullam eligendi eum!
            Voluptatibus qui maxime nostrum consequatur iure voluptate beatae asperiores. Nesciunt, numquam quia? Excepturi, ducimus dolorum quis cupiditate consectetur, itaque non iure quam ipsam aliquam totam vitae ipsum sapiente repellat labore!
        </div>
        @yield('body')
    </div>
</body>

</html>
